"""Frozen PublishedArtifact v2 for the forward-volatility hypothesis.

GENERATED by scripts/msrp/build_forward_vol_artifact.py from the frozen MSRP Phase-1
Research Dossier (commit d9233b1). Do not edit by hand; coefficients are
frozen OLS estimates on the development window 2023-01-02 -> 2025-12-31. Any change
requires a new artifact version under a new pre-registration.

Model (dossier S7, log specification)::

    log RV_{t+1} = b0 + b1 log RV^(d)_t + b2 log RV^(w)_t
                   + b3 log RV^(m)_t + b4 log VIX_t + e_t

Evaluates pre-built Evidence (rv_daily, rv_weekly, rv_monthly, vix_close) into a
MarketState carrying the named estimate "expected_next_day_realized_vol" with state-dependent
uncertainty (Phase-2 finding Mo2).
"""

import math
from datetime import datetime
from typing import Dict, Tuple

from core.msi.contracts.artifact import ArtifactMetadata, PublishedArtifact
from core.msi.contracts.estimate import Estimate
from core.msi.contracts.evidence import Evidence
from core.msi.contracts.market_state import MarketState

# --- Frozen coefficients (dev window 2023-01-02 -> 2025-12-31, OLS) ----------
B0 = -3.7622839907400962
B1 = 0.3122522558049047
B2 = 0.12971992430399976
B3 = 0.0827608552799891
B4 = 0.4758148602543205
SIGMA = 0.27255248237535945
N_OBS = 700

_LATENT_VARIABLE = "expected_next_day_realized_vol"
_DIMENSION = "volatility_level"
_FEATURE_TYPES = ('rv_daily', 'rv_weekly', 'rv_monthly', 'vix_close')

_METADATA = ArtifactMetadata(
    artifact_id="msrp-forward-vol-v2",
    artifact_version="v1.0.0",
    schema_version="1.0",
    validation_id="val-msrp-forward-vol-v2-pending",
    publication_timestamp=datetime(2026, 7, 6, 0, 0, 0),
    compatibility_version="1.0",
    runtime_compatibility="msi-v1.0",
    provenance_reference="prov-msrp-forward-vol-v2",
)

_EVIDENCE_RULES: Dict[str, object] = {
    "features": [
        {
            "name": "rv_daily",
            "source": "NSE_INDEX|Nifty 50",
            "field": "close",
            "transform": "rv_intraday",
            "description": "1-day realized vol: sqrt(sum of squared intraday 1m log-returns)",
        },
        {
            "name": "rv_weekly",
            "source": "NSE_INDEX|Nifty 50",
            "field": "close",
            "transform": "har_weekly_5d",
            "description": "mean of RV over the last 5 trading days (HAR weekly aggregate)",
        },
        {
            "name": "rv_monthly",
            "source": "NSE_INDEX|Nifty 50",
            "field": "close",
            "transform": "har_monthly_22d",
            "description": "mean of RV over the last 22 trading days (HAR monthly aggregate)",
        },
        {
            "name": "vix_close",
            "source": "NSE_INDEX|India VIX",
            "field": "close",
            "transform": "identity",
            "description": "India VIX closing level (option-implied forward vol)",
        },
    ],
    "lookback_days": 22,
    "required_symbols": ["NSE_INDEX|Nifty 50", "NSE_INDEX|India VIX"],
    "rule_format_version": "1.0",
}


class ForwardVolatilityArtifact(PublishedArtifact):
    """Frozen HAR-RV+VIX PublishedArtifact v2 (MSI-007).

    Deterministic: identical Evidence -> identical MarketState. Applies the frozen
    log-linear predictor and emits the named estimate with a state-dependent
    (level-scaled) predictive uncertainty.
    """

    metadata = _METADATA

    def get_evidence_rules(self) -> Dict[str, object]:
        return _EVIDENCE_RULES

    def evaluate(self, evidence: Tuple[Evidence, ...]) -> MarketState:
        values: Dict[str, float] = {}
        for e in evidence:
            values[e.evidence_type] = e.evidence_value

        rv_daily = values.get("rv_daily")
        rv_weekly = values.get("rv_weekly")
        rv_monthly = values.get("rv_monthly")
        vix = values.get("vix_close")
        if not all(v is not None and v > 0.0 for v in (rv_daily, rv_weekly, rv_monthly, vix)):
            raise ValueError(
                "ForwardVolatilityArtifact requires positive rv_daily, rv_weekly, "
                "rv_monthly, vix_close evidence"
            )

        mu = (
            B0
            + B1 * math.log(rv_daily)
            + B2 * math.log(rv_weekly)
            + B3 * math.log(rv_monthly)
            + B4 * math.log(vix)
        )
        value = math.exp(mu + (SIGMA ** 2) / 2.0)
        uncertainty = value * math.sqrt(math.exp(SIGMA ** 2) - 1.0)

        estimate = Estimate(
            latent_variable=_LATENT_VARIABLE,
            value=value,
            uncertainty=uncertainty,
            dimension=_DIMENSION,
        )
        # evaluation_timestamp = the evidence's own as-of date (point-in-time provenance).
        # All four features are required (validated above), so evidence is non-empty here;
        # there is no sentinel floor — a historical evaluation is stamped with its actual
        # evidence date, not a future constant.
        latest_ts = max(e.construction_timestamp for e in evidence)
        return MarketState(evaluation_timestamp=latest_ts, estimates=(estimate,))
