"""N200 regime classifier — substrate preflight.

Read-only. Answers one question before any estimation code is written: does the
local store actually carry what the pre-registered design needs — contiguous
CA-adjusted OHLC for point-in-time N200 members, deep enough for a 252-session
warmup before the first fold, clean enough for Garman-Klass.

Checks:
  1. Price substrate span, rows per year, series composition
  2. Universe membership: cadence, size, method, rebalance gaps
  3. Member -> price coverage (does a member resolve to price rows?)
  4. Warmup depth at each fold boundary
  5. OHLC integrity for Garman-Klass (nulls, non-positive, H<L, O/C outside [L,H])
  6. Trading calendar contiguity
  7. Fold feasibility: usable entities per evaluation year

Usage: python scripts/n200_regime/preflight_substrate.py
Output: docs/reports/index_research/N200_REGIME_SUBSTRATE_PREFLIGHT.md
"""
from __future__ import annotations

from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parents[2]
DB = ROOT / "data" / "market_data" / "equity_bhavcopy.duckdb"
OUT = ROOT / "docs" / "reports" / "index_research" / "N200_REGIME_SUBSTRATE_PREFLIGHT.md"
TMP = Path("C:/Users/devou/AppData/Local/Temp/claude/F--Nifty/duckdb_spill")
TMP.mkdir(parents=True, exist_ok=True)

FOLD_YEARS = list(range(2017, 2027))
WARMUP_SESSIONS = 252
MIN_SEQ_SESSIONS = 60


def q(con, sql, params=None):
    return con.execute(sql, params or []).fetchall()


def main() -> int:
    # Root connection is in-memory: the source is attached READ_ONLY (this
    # preflight never writes to it) while the scratch database is attached
    # writable. Opening the source directly read-only would force every ATTACH
    # under it read-only too, and the scratch table could not be created.
    con = duckdb.connect()
    # `equity_bhavcopy_adjusted` is a VIEW doing entity-grain CA joins — it is
    # recomputed for every query that touches it, which exhausts memory across a
    # dozen checks. Materialize the columns this preflight needs exactly once,
    # with disk spill available, and read `px` thereafter.
    # The box has ~2.6 GB free of 7.9 GB, so the limit is set below what is
    # actually available and the scratch table lands in an attached on-disk
    # database — a TEMP table under a limit larger than free RAM never spills
    # and dies with "Allocation failure".
    con.execute("SET memory_limit='1GB'")
    con.execute("SET threads=2")
    con.execute(f"SET temp_directory='{TMP.as_posix()}'")
    con.execute(f"ATTACH '{DB.as_posix()}' AS src (READ_ONLY)")
    scratch = TMP / "n200_preflight_scratch.duckdb"
    scratch.unlink(missing_ok=True)
    con.execute(f"ATTACH '{scratch.as_posix()}' AS scratch")
    con.execute("CREATE TABLE scratch.px AS SELECT trade_date, symbol, series, "
                "open, high, low, close FROM src.equity_bhavcopy_adjusted")
    con.execute("CREATE INDEX px_sym ON scratch.px (symbol)")
    L: list[str] = []
    w = L.append

    w("# N200 Regime Classifier — Substrate Preflight")
    w("")
    w("Generated by `scripts/n200_regime/preflight_substrate.py`. Read-only; every "
      "number is script-produced. Run before any estimation code, per the "
      "pre-registered design.")
    w("")

    # ── 1. Price substrate ────────────────────────────────────────────────
    n, lo, hi = q(con, "SELECT count(*), min(trade_date), max(trade_date) "
                       "FROM scratch.px")[0]
    w("## 1. Price substrate — `px`")
    w("")
    w(f"**{n:,} rows, {lo} → {hi}.**")
    w("")
    series = q(con, "SELECT series, count(*) c FROM scratch.px "
                    "GROUP BY 1 ORDER BY c DESC LIMIT 6")
    w("| series | rows |")
    w("|---|---:|")
    for s, c in series:
        w(f"| {s} | {c:,} |")
    w("")
    yr = q(con, "SELECT year(trade_date) y, count(*) c, count(DISTINCT symbol) s, "
                "count(DISTINCT trade_date) d FROM scratch.px "
                "GROUP BY 1 ORDER BY 1")
    w("| year | rows | symbols | sessions |")
    w("|---|---:|---:|---:|")
    for y, c, s, d in yr:
        w(f"| {y} | {c:,} | {s:,} | {d} |")
    w("")

    # ── 2. Universe membership ────────────────────────────────────────────
    w("## 2. Universe — `universe_membership`")
    w("")
    un, ulo, uhi = q(con, "SELECT count(*), min(rebalance_date), max(rebalance_date) "
                          "FROM src.universe_membership")[0]
    methods = q(con, "SELECT method, count(*) c, count(DISTINCT rebalance_date) r "
                     "FROM src.universe_membership GROUP BY 1 ORDER BY c DESC")
    nreb = q(con, "SELECT count(DISTINCT rebalance_date) FROM src.universe_membership")[0][0]
    w(f"**{un:,} rows over {nreb} rebalances, {ulo} → {uhi}.**")
    w("")
    w("| method | rows | rebalances |")
    w("|---|---:|---:|")
    for m, c, r in methods:
        w(f"| `{m}` | {c:,} | {r} |")
    w("")
    sizes = q(con, "SELECT count(*) n FROM src.universe_membership GROUP BY rebalance_date")
    ns = sorted(x[0] for x in sizes)
    w(f"Members per rebalance: min {ns[0]}, median {ns[len(ns)//2]}, max {ns[-1]}.")
    w("")
    gaps = q(con, """
        WITH r AS (SELECT DISTINCT rebalance_date d FROM src.universe_membership),
             s AS (SELECT d, lag(d) OVER (ORDER BY d) p FROM r)
        SELECT p, d, date_diff('day', p, d) g FROM s
        WHERE p IS NOT NULL AND date_diff('day', p, d) > 45 ORDER BY g DESC LIMIT 10
    """)
    if gaps:
        w("**Rebalance gaps > 45 days:**")
        w("")
        w("| from | to | days |")
        w("|---|---|---:|")
        for p, d, g in gaps:
            w(f"| {p} | {d} | {g} |")
    else:
        w("No rebalance gap exceeds 45 days — cadence is regular.")
    w("")

    # ── 3. Member -> price coverage ───────────────────────────────────────
    w("## 3. Member → price coverage")
    w("")
    cov = q(con, """
        WITH m AS (SELECT DISTINCT rebalance_date, symbol FROM src.universe_membership),
             hits AS (
               SELECT m.rebalance_date, m.symbol, count(e.trade_date) c
               FROM m LEFT JOIN scratch.px e
                 ON e.symbol = m.symbol
                AND e.trade_date > m.rebalance_date
                AND e.trade_date <= m.rebalance_date + INTERVAL 35 DAY
               GROUP BY 1, 2)
        SELECT year(rebalance_date) y, count(*) members,
               sum(CASE WHEN c = 0 THEN 1 ELSE 0 END) missing
        FROM hits GROUP BY 1 ORDER BY 1
    """)
    w("Members with **zero** price rows in the 35 days after their rebalance:")
    w("")
    w("| year | members | missing | miss rate |")
    w("|---|---:|---:|---:|")
    tot_m = tot_x = 0
    for y, mm, xx in cov:
        tot_m += mm
        tot_x += xx
        w(f"| {y} | {mm:,} | {xx} | {xx/mm:.3%} |")
    w(f"| **all** | **{tot_m:,}** | **{tot_x}** | **{tot_x/tot_m:.3%}** |")
    w("")

    # ── 4. Warmup depth at fold boundaries ────────────────────────────────
    w("## 4. Warmup depth at each fold boundary")
    w("")
    w(f"A name contributes to fold year *T* only with ≥ {WARMUP_SESSIONS} prior "
      f"sessions before {WARMUP_SESSIONS//252} year(s) of history ends at T-1.")
    w("")
    w("| fold year | members at entry | with ≥252 prior sessions | eligible |")
    w("|---|---:|---:|---:|")
    fold_rows = []
    for T in FOLD_YEARS:
        rows = q(con, """
            WITH latest AS (
              SELECT max(rebalance_date) d FROM src.universe_membership
              WHERE rebalance_date < make_date(?, 1, 1)),
            mem AS (
              SELECT symbol FROM src.universe_membership
              WHERE rebalance_date = (SELECT d FROM latest)),
            depth AS (
              SELECT m.symbol, count(e.trade_date) c
              FROM mem m LEFT JOIN scratch.px e
                ON e.symbol = m.symbol AND e.trade_date < make_date(?, 1, 1)
              GROUP BY 1)
            SELECT count(*), sum(CASE WHEN c >= ? THEN 1 ELSE 0 END) FROM depth
        """, [T, T, WARMUP_SESSIONS])[0]
        tot, ok = rows[0], int(rows[1] or 0)
        fold_rows.append((T, tot, ok))
        w(f"| {T} | {tot} | {ok} | {ok/tot:.1%} |")
    w("")

    # ── 5. OHLC integrity for Garman-Klass ────────────────────────────────
    w("## 5. OHLC integrity (Garman-Klass preconditions)")
    w("")
    bad = q(con, """
        SELECT
          count(*) n,
          sum(CASE WHEN open IS NULL OR high IS NULL OR low IS NULL
                     OR close IS NULL THEN 1 ELSE 0 END) n_null,
          sum(CASE WHEN open <= 0 OR high <= 0 OR low <= 0 OR close <= 0
                   THEN 1 ELSE 0 END) nonpos,
          sum(CASE WHEN high < low THEN 1 ELSE 0 END) hl,
          sum(CASE WHEN open > high OR open < low THEN 1 ELSE 0 END) obad,
          sum(CASE WHEN close > high OR close < low THEN 1 ELSE 0 END) cbad,
          sum(CASE WHEN high = low THEN 1 ELSE 0 END) flat
        FROM scratch.px
    """)[0]
    n_all, n_null, nonpos, hl, obad, cbad, flat = bad
    w("| check | rows | share |")
    w("|---|---:|---:|")
    for label, v in [("NULL in O/H/L/C", n_null), ("non-positive price", nonpos),
                     ("high < low", hl), ("open outside [low, high]", obad),
                     ("close outside [low, high]", cbad),
                     ("high == low (zero range)", flat)]:
        w(f"| {label} | {v:,} | {v/n_all:.4%} |")
    w("")
    gk = q(con, """
        SELECT
          sum(CASE WHEN 0.5 * pow(ln(high / low), 2)
                        - (2 * ln(2) - 1) * pow(ln(close / open), 2) = 0
                   THEN 1 ELSE 0 END) zero_gk,
          sum(CASE WHEN 0.5 * pow(ln(high / low), 2)
                        - (2 * ln(2) - 1) * pow(ln(close / open), 2) < 0
                   THEN 1 ELSE 0 END) neg_gk
        FROM scratch.px
        WHERE high > 0 AND low > 0 AND open > 0 AND close > 0 AND high >= low
    """)[0]
    zero_gk, neg_gk = int(gk[0] or 0), int(gk[1] or 0)
    w(f"Garman-Klass variance **= 0: {zero_gk:,} rows ({zero_gk/n_all:.4%})**; "
      f"**< 0: {neg_gk:,} rows ({neg_gk/n_all:.4%})**.")
    w("")
    w("With no row carrying open or close outside [low, high], a zero-range row "
      "forces O = C = H = L, so Garman-Klass is exactly zero there rather than "
      "negative. That is the case the feature build must handle: `log(GK / median)` "
      "is undefined at zero. These are circuit-locked or untraded sessions, and the "
      "pre-registered treatment is to floor GK at each stock's 1st percentile of "
      "its own non-zero GK before the log — pinned here, before any fitting.")
    w("")
    # ── 6. Calendar contiguity ────────────────────────────────────────────
    w("## 6. Trading calendar contiguity")
    w("")
    cgaps = q(con, """
        WITH s AS (SELECT trade_date d, lag(trade_date) OVER (ORDER BY trade_date) p
                   FROM src.trading_calendar)
        SELECT p, d, date_diff('day', p, d) g FROM s
        WHERE p IS NOT NULL AND date_diff('day', p, d) > 5 ORDER BY g DESC LIMIT 8
    """)
    cn, clo, chi = q(con, "SELECT count(*), min(trade_date), max(trade_date) "
                          "FROM src.trading_calendar")[0]
    w(f"{cn:,} sessions, {clo} → {chi}.")
    w("")
    if cgaps:
        w("| from | to | days |")
        w("|---|---|---:|")
        for p, d, g in cgaps:
            w(f"| {p} | {d} | {g} |")
    else:
        w("No calendar gap exceeds 5 days.")
    w("")

    # ── 7. Fold feasibility ───────────────────────────────────────────────
    w("## 7. Fold feasibility summary")
    w("")
    w("| fold year | eligible names | panel obs (approx, 250 sess/name) |")
    w("|---|---:|---:|")
    for T, _tot, ok in fold_rows:
        w(f"| {T} | {ok} | {ok*250:,} |")
    w("")
    total_obs = sum(ok for _, _, ok in fold_rows) * 250
    w(f"Approximate total filtered observations across all folds: **{total_obs:,}**.")
    w("")

    con.close()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    # Windows consoles are cp1252; the report on disk is UTF-8 regardless.
    print("\n".join(L).encode("ascii", "replace").decode("ascii"))
    print(f"\nWritten: {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
