"""Can the DayType label generator be re-run, and does it reproduce its labels?

Finding B of `docs/reports/index_research/REGIME_DETECTION_SPEC_AUDIT_2026-09-09.md`:
`cluster_day_types.py` persists `cluster_labels.csv` but never persists the
scaler, PCA or KMeans objects that produced it. So the target definition the
shipped classifier was trained against cannot be re-derived, and the live
nearest-centroid proxy is not commensurable with the trained label.

This script answers the empirical half of that finding. It re-runs the clustering
pipeline through the same functions `cluster_day_types.py` calls, and compares the
regenerated labels with the stored ones.

**Copy-first: it writes nothing to `data/features/day_type/`.** The stored labels
are the training target of a model in production; a verification run must not be
able to move them.

**Predictions, pinned before the run:**

  P1  The pipeline re-runs to completion on today's data and code.
  P2  It selects k = 3, matching the shipped CLUSTER_NAMES mapping.
  P3  Under the best label permutation, regenerated labels agree with the stored
      labels on >= 99% of dates. Anything materially below that means the target
      definition is not recoverable, and the shipped model's holdout accuracy is
      measured against labels nothing in the repo can reproduce.
  P4  The best permutation is the identity. If it is not, cluster ids have moved
      since the labels were written, which is label switching in the artifact
      that CLUSTER_NAMES hardcodes -- the exact failure the audit predicts when a
      fit is not persisted.

P3 and P4 are independent: the pipeline can partition the panel identically and
still name the parts differently.

Usage: python scripts/daytype/verify_label_reproducibility.py
Output: docs/reports/index_research/DAYTYPE_LABEL_REPRODUCIBILITY.md
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.optimize import linear_sum_assignment

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from scripts.daytype.cluster_day_types import (  # noqa: E402
    DATA_DIR, apply_pca, apply_winsorization, auto_select_k, load_features,
    prepare_feature_matrix, prune_columns, select_k,
)

STORED = DATA_DIR / "cluster_labels.csv"
OUT = ROOT / "docs" / "reports" / "index_research" / "DAYTYPE_LABEL_REPRODUCIBILITY.md"
PCA_THRESHOLD = 0.87
SHIPPED_K = 3
AGREEMENT_TARGET = 0.99


def best_permutation(stored: np.ndarray, fresh: np.ndarray,
                     k: int) -> tuple[dict, float, float]:
    """Hungarian match on the confusion matrix.

    KMeans cluster ids are arbitrary, so a perfect re-partition can still carry
    different numbers. Raw agreement and best-permutation agreement are reported
    separately for that reason.
    """
    conf = np.zeros((k, k), dtype=int)
    for a, b in zip(stored, fresh):
        if 0 <= a < k and 0 <= b < k:
            conf[a, b] += 1
    row, col = linear_sum_assignment(-conf)
    mapping = {int(c): int(r) for r, c in zip(row, col)}
    matched = conf[row, col].sum()
    raw = float((stored == fresh).mean())
    return mapping, float(matched / len(stored)), raw


def main() -> int:
    L: list[str] = []
    w = L.append
    w("# DayType — Is the Label Generator Reproducible?")
    w("")
    w("Generated by `scripts/daytype/verify_label_reproducibility.py`. Read-only "
      "against `data/features/day_type/`; the stored labels are a production "
      "model's training target and this run cannot move them.")
    w("")
    w("Answers the empirical half of Finding B in "
      "`REGIME_DETECTION_SPEC_AUDIT_2026-09-09.md`. Predictions P1-P4 were pinned "
      "in the script docstring before the run.")
    w("")

    stored_df = pd.read_csv(STORED, index_col=0, parse_dates=True)
    w(f"Stored labels: **{len(stored_df):,} sessions**, "
      f"{stored_df.index.min():%Y-%m-%d} to {stored_df.index.max():%Y-%m-%d}.")
    w("")

    print("[1] Re-running the clustering pipeline...")
    df_raw = load_features()
    df_pruned = prune_columns(df_raw)
    df_wins = apply_winsorization(df_pruned)
    X_scaled, feature_names, df_clean, _scaler = prepare_feature_matrix(df_wins, 1.0)
    X_pca, pca, n_components = apply_pca(X_scaled, PCA_THRESHOLD)
    k_results = select_k(X_pca)
    k_best = auto_select_k(k_results)
    fresh = pd.Series(k_results[k_best]["labels"], index=df_clean.index)

    w("## 1. P1 — does the pipeline re-run?")
    w("")
    w(f"**Yes.** {len(df_raw):,} feature rows loaded, {df_pruned.shape[1]} columns "
      f"after pruning, {len(feature_names)} numeric features on "
      f"{X_scaled.shape[0]:,} complete rows, PCA retained **{n_components} "
      f"components** at the {PCA_THRESHOLD:.0%} threshold.")
    w("")

    w("## 2. P2 — does it select the shipped k?")
    w("")
    w(f"Auto-selected **k = {k_best}**; the shipped `CLUSTER_NAMES` mapping assumes "
      f"k = {SHIPPED_K}. P2 **{'holds' if k_best == SHIPPED_K else 'FAILS'}**.")
    w("")
    w("| k | silhouette | Calinski-Harabasz | Davies-Bouldin | min cluster |")
    w("|---|---:|---:|---:|---:|")
    for k, v in k_results.items():
        w(f"| {k} | {v['sil']:.4f} | {v['ch']:.1f} | {v['db']:.4f} | "
          f"{v['min_pct']:.1%} |")
    w("")

    joined = stored_df.join(fresh.rename("fresh"), how="inner").dropna(
        subset=["cluster_id", "fresh"])
    s = joined["cluster_id"].astype(int).to_numpy()
    f = joined["fresh"].astype(int).to_numpy()

    w("## 3. P3 / P4 — do the labels agree?")
    w("")
    w(f"Dates present in both the stored file and this run: **{len(joined):,}** "
      f"(stored has {len(stored_df):,}; this run produced {len(fresh):,}).")
    w("")

    if k_best != SHIPPED_K:
        w(f"**Comparison not attempted.** The run selected k = {k_best} against the "
          f"stored file's {SHIPPED_K}, so there is no label correspondence to "
          "measure. P3 and P4 are undefined, and that is itself the finding: the "
          "pipeline does not return to the configuration its own stored output was "
          "produced under.")
        agree_perm = raw = float("nan")
        mapping, identity = {}, False
    else:
        mapping, agree_perm, raw = best_permutation(s, f, SHIPPED_K)
        identity = all(k == v for k, v in mapping.items())
        w(f"- Raw agreement, ids as written: **{raw:.4f}**")
        w(f"- Best-permutation agreement: **{agree_perm:.4f}** "
          f"(P3 target >= {AGREEMENT_TARGET:.2f} — "
          f"**{'met' if agree_perm >= AGREEMENT_TARGET else 'NOT met'}**)")
        w(f"- Best permutation (fresh -> stored): `{mapping}` — identity: "
          f"**{identity}** (P4 {'holds' if identity else 'FAILS'})")
        w("")
        conf = pd.crosstab(pd.Series(s, name="stored"), pd.Series(f, name="fresh"))
        w("Confusion matrix (rows stored, columns regenerated):")
        w("")
        w("| stored \\ fresh | " + " | ".join(str(c) for c in conf.columns) + " |")
        w("|---|" + "---:|" * len(conf.columns))
        for i, row in conf.iterrows():
            w(f"| {i} | " + " | ".join(f"{int(v):,}" for v in row) + " |")
    w("")

    w("## 4. Reading")
    w("")
    if k_best == SHIPPED_K and agree_perm >= AGREEMENT_TARGET and identity:
        w("The pipeline reproduces its own stored labels. Finding B's *practical* "
          "severity is lower than feared — the target definition is recoverable by "
          "re-running — but the defect stands: nothing in the repo persists the "
          "fitted objects, so this agreement is a property of today's data and "
          "library versions and is not guaranteed to survive either changing.")
    elif k_best == SHIPPED_K and agree_perm >= AGREEMENT_TARGET:
        w("The pipeline re-partitions the panel the same way but **names the parts "
          "differently**. `CLUSTER_NAMES` in `train_daytype_classifier.py` is a "
          "hardcoded id-to-name map, so a regenerated label file would silently "
          "invert the meaning of the shipped model's classes. This is label "
          "switching in exactly the place the audit predicted.")
    else:
        w("The stored labels **cannot be reproduced** by re-running the pipeline. "
          "The shipped classifier's training target, and every accuracy figure "
          "measured against it, rests on an artifact nothing in the repo can "
          "regenerate. Repairing this means persisting the fit going forward and "
          "treating the existing labels as an unreproducible legacy input that must "
          "be either retired or frozen with that status recorded.")
    w("")
    w("Either way the forward fix is the same and is unchanged by this result: "
      "`cluster_day_types.py` must persist its scaler, PCA and KMeans as plain "
      "arrays with a hash, so the next answer to this question is a file lookup "
      "rather than a re-run.")
    w("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print("\n".join(L).encode("ascii", "replace").decode("ascii"))
    print(f"\nWritten: {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
