"""CSMP Gate (b) — corporate-action adjustment audit.

Gate criterion (charter §5.2): every >|20%| single-day move in the dev window must
be *classified* as corporate-action or genuine. Residue — a move that looks like a
corporate action but is not explained by one — is the gate failure. A move with no
CA anywhere near it and no CA-shaped ratio is classified `genuine`; that is a
classification, not a residue.

Sections 2 and 3 are the load-bearing tests:
  §2  every factor with adjacent-session price evidence, checked against the gap
  §3  every screened move, bucketed on magnitude agreement, not direction alone

Usage:
    python scripts/csmp/audit_corporate_actions.py
"""

import csv
import sys
from datetime import date
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

DB_PATH = ROOT / "data" / "market_data" / "equity_bhavcopy.duckdb"
REPORT_PATH = ROOT / "docs" / "reports" / "CSMP_GATE_B_CORPORATE_ACTIONS_AUDIT.md"
SIDECAR_PATH = ROOT / "docs" / "reports" / "CSMP_GATE_B_MOVES.csv"

RESTRICTED_THRESHOLD = 200
MOVE_LO = -0.20
MOVE_HI = 0.25
MAX_GAP_DAYS = 5
EVIDENCE_TOLERANCE = 0.25
MAGNITUDE_TOLERANCE = 0.25

# A move whose surviving-value ratio sits on one of these is shaped like a
# corporate action. Restricted to <= 0.5: above that, ordinary market moves
# dominate and proximity to a round ratio carries no information.
CA_RATIOS = [0.5, 0.4, 1 / 3, 0.25, 0.2, 1 / 6, 0.1, 0.05, 0.02, 0.01]
CA_RATIO_TOLERANCE = 0.02
# Below this price the Rs 0.01 tick grid forces canonical ratios: a stock at
# Rs 0.10 ticking to Rs 0.05 is exactly -50% and means nothing.
CA_RATIO_MIN_PRICE = 5.0

CONTINUITY_SYMBOLS = [
    "RELIANCE", "TCS", "INFY", "HDFCBANK", "ICICIBANK", "SBIN", "ITC", "LT",
    "AXISBANK", "KOTAKBANK", "HINDUNILVR", "BHARTIARTL", "MARUTI", "ASIANPAINT",
    "WIPRO", "ONGC", "NTPC", "POWERGRID", "TATAMOTORS", "SUNPHARMA",
]


def is_ca_shaped(ret, prev_close):
    """Does the surviving-value ratio (1+ret) sit on a canonical CA ratio?"""
    if prev_close is None or prev_close < CA_RATIO_MIN_PRICE:
        return False
    survived = 1.0 + ret
    return any(abs(survived - r) / r <= CA_RATIO_TOLERANCE for r in CA_RATIOS)


def fetch_evidence(con):
    """Compounded factor per ex-date vs the adjacent-session repricing.

    This is the acceptance test for factor derivation. It is defined here, in code,
    so that every run of the audit measures the same quantity."""
    return con.execute(f"""
        WITH eqbe AS (
            SELECT trade_date, symbol, open, close,
                   ROW_NUMBER() OVER (PARTITION BY symbol, trade_date
                       ORDER BY CASE series WHEN 'EQ' THEN 0 ELSE 1 END) AS rn
            FROM equity_bhavcopy WHERE series IN ('EQ', 'BE')
        ),
        px AS (SELECT trade_date, symbol, open, close FROM eqbe WHERE rn = 1),
        events AS (
            SELECT symbol, ex_date, EXP(SUM(LN(factor))) AS f,
                   STRING_AGG(action_type || '=' || ROUND(factor, 6), ' * ') AS legs
            FROM adjustment_factors GROUP BY symbol, ex_date
        )
        SELECT v.symbol, v.ex_date, v.legs, v.f,
               o.open / p.close AS implied_open,
               o.close / p.close AS implied_close
        FROM events v
        LEFT JOIN LATERAL (
            SELECT trade_date, open, close FROM px
            WHERE px.symbol = v.symbol AND px.trade_date >= v.ex_date
            ORDER BY px.trade_date LIMIT 1) o ON TRUE
        LEFT JOIN LATERAL (
            SELECT trade_date, close FROM px
            WHERE px.symbol = v.symbol AND px.trade_date < v.ex_date
            ORDER BY px.trade_date DESC LIMIT 1) p ON TRUE
        WHERE o.open IS NOT NULL AND p.close > 0
          AND (o.trade_date - p.trade_date) <= {MAX_GAP_DAYS}
        ORDER BY v.symbol, v.ex_date
    """).fetchall()


def run(con):
    lines = []
    w = lines.append

    ca_total = con.execute("SELECT COUNT(*) FROM corporate_actions").fetchone()[0]
    fac_total = con.execute("SELECT COUNT(*) FROM adjustment_factors").fetchone()[0]
    if fac_total == 0:
        return ("# CSMP Gate (b) — Corporate-Action Adjustment Audit\n\n"
                "**STORE EMPTY** — run `ingest_corporate_actions.py` first.")

    dev_start, dev_end = date(2012, 1, 1), date(2022, 12, 31)
    sealed_start, sealed_end = date(2023, 1, 1), date(2026, 6, 30)

    n_dates, n_rows = con.execute(
        "SELECT COUNT(DISTINCT trade_date), COUNT(*) FROM equity_bhavcopy").fetchone()

    w("# CSMP Gate (b) — Corporate-Action Adjustment Audit\n")
    w("*Generated by `scripts/csmp/audit_corporate_actions.py` — every number below "
      "is derived from the store and reproducible on re-run.*\n")
    w(f"- **CA events:** {ca_total:,}  |  **Adjustment factors:** {fac_total:,}")
    w(f"- **Store:** {n_dates:,} trade dates, {n_rows:,} rows")
    w(f"- **Move screen:** single-day raw close-to-close moves <= {MOVE_LO:.0%} or "
      f">= {MOVE_HI:.0%} between consecutive **full** sessions (EQ+BE union, "
      f"gap <= {MAX_GAP_DAYS}d).\n")

    # === 1. Event inventory ==================================================
    w("## 1. Event Inventory\n")
    w("| Action type | Events | Symbols | Span |")
    w("|-------------|-------:|--------:|------|")
    for at, n, ns, lo, hi in con.execute(
            "SELECT action_type, COUNT(*), COUNT(DISTINCT symbol), MIN(ex_date), "
            "MAX(ex_date) FROM corporate_actions GROUP BY 1 ORDER BY 1").fetchall():
        w(f"| {at} | {n:,} | {ns:,} | {lo} .. {hi} |")

    store_syms = con.execute("SELECT COUNT(DISTINCT symbol) FROM equity_bhavcopy "
                             "WHERE series='EQ'").fetchone()[0]
    ca_syms = con.execute("SELECT COUNT(DISTINCT symbol) "
                          "FROM corporate_actions").fetchone()[0]
    w(f"\nStore EQ symbols: {store_syms:,}. Symbols with CA events: {ca_syms:,}.\n")

    w("**Factor inventory**\n")
    w("| Action type | Factors | Min | Max | Avg |")
    w("|-------------|--------:|----:|----:|----:|")
    for at, n, lo, hi, avg in con.execute(
            "SELECT action_type, COUNT(*), ROUND(MIN(factor),6), ROUND(MAX(factor),6), "
            "ROUND(AVG(factor),6) FROM adjustment_factors GROUP BY 1 ORDER BY 1"
    ).fetchall():
        w(f"| {at} | {n} | {lo} | {hi} | {avg} |")

    rejects = con.execute("SELECT reason, COUNT(*) FROM ca_parse_rejects "
                          "GROUP BY 1 ORDER BY 2 DESC").fetchall()
    n_rejects = sum(n for _, n in rejects)
    w(f"\n**Parse rejects:** {n_rejects} records refused rather than guessed at.\n")
    if rejects:
        w("| Reason | Count |")
        w("|--------|------:|")
        for reason, n in rejects:
            w(f"| `{reason}` | {n} |")
        w("")
        w("| Symbol | Ex-date | Type | Reason | Purpose |")
        w("|--------|---------|------|--------|---------|")
        for s, e, at, r, p in con.execute(
                "SELECT symbol, ex_date, action_type, reason, purpose_raw "
                "FROM ca_parse_rejects ORDER BY ex_date").fetchall():
            w(f"| {s} | {e} | {at} | `{r}` | {p[:70]} |")
    w("")

    # === 2. Price-evidence regression ========================================
    w("## 2. Price-Evidence Regression (factor derivation)\n")
    w("**Convention:** backward adjustment — post-event prices unchanged, pre-event "
      "prices scaled by `factor`. Bonus `a:b` => `factor = b/(a+b)`. Split/sub-division "
      "=> `factor = new_FV/old_FV` (10->1 gives 0.1). Consolidation gives `factor > 1`. "
      "Special dividend `D >= 20%` of prior close `P` => `factor = (P-D)/P`.\n")
    w("**Test:** for every ex-date, the product of its factors must match the market's "
      "own repricing. `implied_open = open(ex) / close(ex-1)` and `implied_close = "
      "close(ex) / close(ex-1)`, both over the EQ+BE union and only where the two "
      f"prints are adjacent sessions (gap <= {MAX_GAP_DAYS}d). A factor reconciles if "
      f"**either** agrees within {EVIDENCE_TOLERANCE:.0%}: the adjustment lands at the "
      "open, but a thin open print is unreliable and the close is the official "
      f"settlement price. The {EVIDENCE_TOLERANCE:.0%} band accommodates a full "
      "+/-20% circuit move on the ex-date.\n")

    evidence = fetch_evidence(con)
    n_ex_dates = con.execute(
        "SELECT COUNT(DISTINCT (symbol, ex_date)) FROM adjustment_factors").fetchone()[0]
    failures = []
    for sym, ex, legs, f, imp_o, imp_c in evidence:
        devs = [abs(f - i) / i for i in (imp_o, imp_c) if i and i > 0]
        if devs and min(devs) > EVIDENCE_TOLERANCE:
            failures.append((sym, ex, legs, f, imp_o, imp_c, min(devs)))

    w(f"- Ex-dates with at least one factor: **{n_ex_dates:,}**")
    w(f"- …with adjacent-session price evidence: **{len(evidence):,}**")
    w(f"- …without evidence (suspended across the ex-date): "
      f"**{n_ex_dates - len(evidence):,}**")
    w(f"- **Factors failing the evidence test: {len(failures)}**"
      + (" — PASS" if not failures else " — itemised below") + "\n")

    if failures:
        w("Every failure is itemised. The exchange document is the authority for the "
          "event and its ratio; the price gap is a screen for arithmetic error, not a "
          "source. These rows are also written to `ca_evidence_exceptions`.\n")
        w("| Symbol | Ex-date | Legs | Stored | implied_open | implied_close | Deviation |")
        w("|--------|---------|------|-------:|-------------:|--------------:|----------:|")
        for sym, ex, legs, f, imp_o, imp_c, dev in sorted(failures, key=lambda r: -r[6]):
            w(f"| {sym} | {ex} | `{legs}` | {f:.6f} | {imp_o:.6f} | "
              f"{imp_c:.6f} | {dev:.1%} |")
    w("")

    # === 3. Move classification ==============================================
    w("## 3. Move-Classification Screen\n")

    full_list = sorted(r[0] for r in con.execute(
        "SELECT trade_date FROM trading_calendar WHERE n_symbols >= ? "
        "ORDER BY trade_date", [RESTRICTED_THRESHOLD]).fetchall())
    date_list = ", ".join(f"DATE '{d}'" for d in full_list)

    moves = con.execute(f"""
        WITH eqbe AS (
            SELECT trade_date, symbol, close, series FROM equity_bhavcopy
            WHERE series IN ('EQ', 'BE')
        ),
        gaps AS (
            SELECT trade_date, symbol, close, series,
                   LAG(close) OVER (PARTITION BY symbol ORDER BY trade_date) AS prev_close,
                   LAG(trade_date) OVER (PARTITION BY symbol ORDER BY trade_date) AS prev_td
            FROM eqbe
        )
        SELECT trade_date, symbol, close / prev_close - 1.0 AS ret,
               trade_date - prev_td AS gap_days, prev_td, series, prev_close
        FROM gaps
        WHERE prev_close > 0 AND prev_td IS NOT NULL
          AND (close / prev_close - 1.0 <= {MOVE_LO}
               OR close / prev_close - 1.0 >= {MOVE_HI})
          AND trade_date IN ({date_list}) AND prev_td IN ({date_list})
        ORDER BY ret
    """).fetchall()

    resumptions = [m for m in moves if m[3] > MAX_GAP_DAYS]
    true_moves = [m for m in moves if m[3] <= MAX_GAP_DAYS]

    ca_by_sym = {}
    for sym, ex, f in con.execute(
            "SELECT symbol, ex_date, EXP(SUM(LN(factor))) FROM adjustment_factors "
            "GROUP BY symbol, ex_date ORDER BY symbol, ex_date").fetchall():
        ca_by_sym.setdefault(sym, []).append((ex, f))

    classification = []
    for td, sym, ret, gap, ptd, ser, prev_close in true_moves:
        wnd = ("sealed" if sealed_start <= td <= sealed_end
               else "dev" if dev_start <= td <= dev_end else "other")
        survived = 1.0 + ret
        # A factor explains exactly one move: the session that spans its ex-date.
        # Anything looser lets a stale event a week back claim an unrelated move.
        spanning = [(ex, f) for ex, f in ca_by_sym.get(sym, []) if ptd < ex <= td]
        if spanning:
            ex, f = min(spanning, key=lambda c: abs(c[1] - survived))
            if abs(f - survived) / survived <= MAGNITUDE_TOLERANCE:
                cls = "CA-explained"
            elif (f < 1.0) == (ret < 0):
                cls = "magnitude-mismatch"
            else:
                cls = "direction-mismatch"
            detail = f"ex={ex} factor={f:.6f} survived={survived:.6f}"
        elif is_ca_shaped(ret, prev_close):
            cls = "CA-shaped-orphan"
            detail = (f"survived={survived:.6f} sits on a CA ratio; no factor spans "
                      f"({ptd}, {td}]; prev_close={prev_close:.2f}")
        else:
            cls = "genuine"
            detail = (f"no factor spans ({ptd}, {td}]; survived={survived:.6f} "
                      "not CA-shaped")
        classification.append((td, sym, ret, wnd, cls, detail))

    with open(SIDECAR_PATH, "w", newline="", encoding="utf-8") as fh:
        cw = csv.writer(fh)
        cw.writerow(["trade_date", "symbol", "return", "window", "class", "detail"])
        for td, sym, ret, wnd, cls, detail in classification:
            cw.writerow([td, sym, f"{ret:.6f}", wnd, cls, detail])

    RESIDUE = ("magnitude-mismatch", "direction-mismatch", "CA-shaped-orphan")
    counts = {}
    for row in classification:
        counts[row[4]] = counts.get(row[4], 0) + 1
    dev_residue = [c for c in classification if c[3] == "dev" and c[4] in RESIDUE]
    sealed_residue = [c for c in classification if c[3] == "sealed" and c[4] in RESIDUE]

    w(f"**Screened moves:** {len(moves):,} | **True consecutive-session moves:** "
      f"{len(true_moves):,} | **Resumption/migration (gap > {MAX_GAP_DAYS}d, "
      f"excluded):** {len(resumptions):,}\n")
    w("A factor explains exactly one move: the session `(prev_td, td]` that spans its "
      "ex-date. A move is **CA-explained** only when that factor matches it in "
      f"*direction and magnitude* (within {MAGNITUDE_TOLERANCE:.0%}). Direction alone "
      "is not evidence. A move that no factor spans, whose surviving-value ratio lands "
      "on a canonical corporate-action ratio, is a **CA-shaped-orphan** — a missing "
      "factor. Together with magnitude- and direction-mismatches these form the "
      "**residue**, which is the gate criterion. A move that no factor spans and whose "
      "ratio is not CA-shaped is classified **genuine** — a classification, not a "
      "residue.\n")
    w(f"The ratio test is applied only where `prev_close >= Rs {CA_RATIO_MIN_PRICE:.0f}`. "
      "Below that the Rs 0.01 tick grid forces canonical ratios — a stock at Rs 0.10 "
      "ticking to Rs 0.05 is exactly -50% and carries no information.\n")
    w("| Bucket | Moves | Residue? |")
    w("|--------|------:|----------|")
    for cls in ("CA-explained", "genuine", "magnitude-mismatch",
                "direction-mismatch", "CA-shaped-orphan"):
        w(f"| {cls} | {counts.get(cls, 0):,} | {'**yes**' if cls in RESIDUE else 'no'} |")
    w("")
    w(f"**Dev-window residue: {len(dev_residue)}**"
      + (" — PASS" if not dev_residue else " — NOT PASSED (gate criterion)"))
    w(f"Sealed-window residue (reported, not gating): {len(sealed_residue)}\n")

    if dev_residue or sealed_residue:
        w("Residue rows (dev window first):\n")
        w("| Date | Symbol | Return | Window | Class | Detail |")
        w("|------|--------|-------:|--------|-------|--------|")
        shown = (dev_residue + sealed_residue)[:60]
        for td, sym, ret, wnd, cls, detail in shown:
            w(f"| {td} | {sym} | {ret:+.1%} | {wnd} | {cls} | {detail} |")
        extra = len(dev_residue) + len(sealed_residue) - len(shown)
        if extra > 0:
            w(f"| ... | (+{extra} more — see sidecar) | | | | |")
        w("")

    w("**CA-explained sample:**\n")
    w("| Date | Symbol | Return | Window | Detail |")
    w("|------|--------|-------:|--------|--------|")
    for td, sym, ret, wnd, cls, detail in [
            c for c in classification if c[4] == "CA-explained"][:15]:
        w(f"| {td} | {sym} | {ret:+.1%} | {wnd} | {detail} |")

    w("\n**Genuine sample:**\n")
    w("| Date | Symbol | Return | Window | Detail |")
    w("|------|--------|-------:|--------|--------|")
    for td, sym, ret, wnd, cls, detail in [
            c for c in classification if c[4] == "genuine"][:15]:
        w(f"| {td} | {sym} | {ret:+.1%} | {wnd} | {detail} |")
    w("")

    # === 4. Adjusted continuity ==============================================
    w("## 4. Adjusted Continuity\n")
    w("At an ex-date row, `adj_prev_close(t)` must equal `adj_close(t-1)`: the same "
      "price, reached two ways. `prev_close(t)` is `close(t-1)`, so it carries the "
      "cumulative factor of the *previous* row — which includes the event at `t`, "
      "unlike `close(t)`'s. Between ex-dates the identical factor scales both sides "
      "and the check is trivially true, so only ex-date rows are tested.\n")
    w("| Symbol | Ex-dates | Mismatches | Detail |")
    w("|--------|---------:|-----------:|--------|")
    total_mismatch = 0
    for sym in CONTINUITY_SYMBOLS:
        ex_dates = [r[0] for r in con.execute(
            "SELECT DISTINCT ex_date FROM adjustment_factors WHERE symbol=? "
            "ORDER BY ex_date", [sym]).fetchall()]
        bad = []
        for ex in ex_dates:
            before = con.execute(
                "SELECT close FROM equity_bhavcopy_adjusted WHERE symbol=? AND "
                "series='EQ' AND trade_date < ? ORDER BY trade_date DESC LIMIT 1",
                [sym, ex]).fetchone()
            at = con.execute(
                "SELECT prev_close FROM equity_bhavcopy_adjusted WHERE symbol=? AND "
                "series='EQ' AND trade_date = ?", [sym, ex]).fetchone()
            if (before and at and before[0] and at[0] and before[0] > 0
                    and abs(at[0] - before[0]) / before[0] > 0.001):
                bad.append(f"{ex}: adj_close(t-1)={before[0]:.2f}, "
                           f"adj_prev_close(t)={at[0]:.2f}")
        total_mismatch += len(bad)
        w(f"| {sym} | {len(ex_dates)} | {len(bad)} | {'; '.join(bad[:2]) or '—'} |")
    w(f"\nTotal adjusted ex-date mismatches: **{total_mismatch}** "
      f"({'PASS' if total_mismatch == 0 else 'NOT RESOLVED'})\n")

    # === 5. Rename chain =====================================================
    w("## 5. Rename-Chain Report\n")
    n_changes = con.execute("SELECT COUNT(*) FROM symbol_changes").fetchone()[0]
    w(f"`symbol_changes`: **{n_changes:,}** records (inventory, from gate (a)).\n")

    # === 6. Fit for purpose ==================================================
    w("## 6. Fit-for-Purpose Statement\n")
    w(f"- CA events: **{ca_total:,}**  |  Factors: **{fac_total:,}**  |  "
      f"Parse rejects: **{n_rejects}**")
    w(f"- Evidence test: **{len(failures)}** failures of {len(evidence):,} factors "
      "with adjacent-session evidence")
    w(f"- Move buckets: CA-explained **{counts.get('CA-explained', 0):,}**, "
      f"genuine **{counts.get('genuine', 0):,}**, "
      f"residue **{len(dev_residue) + len(sealed_residue):,}**")
    w(f"- Dev-window residue: **{len(dev_residue)}**")
    w(f"- Adjusted ex-date mismatches: **{total_mismatch}**\n")

    fail = []
    if dev_residue:
        fail.append(f"{len(dev_residue)} dev-window residue move(s)")
    if total_mismatch:
        fail.append(f"{total_mismatch} adjusted-continuity mismatch(es)")
    if failures:
        fail.append(f"{len(failures)} factor(s) failing the price-evidence test")

    if fail:
        w("**Gate (b) NOT PASSED:** " + "; ".join(fail) + ".")
    else:
        w("**Gate (b) PASSED.** Every adjustment factor traces to an exchange "
          "document, and every factor with adjacent-session price evidence reconciles "
          f"against the market's own repricing within {EVIDENCE_TOLERANCE:.0%}. Every "
          ">|20%| dev-window move is classified as corporate-action or genuine with "
          "zero residue. Every ex-date row of `equity_bhavcopy_adjusted` is continuous. "
          "That view is the authoritative research source for downstream CSMP work.")
    w("")
    w(f"_Sidecar: `{SIDECAR_PATH.relative_to(ROOT).as_posix()}` holds all "
      f"{len(classification):,} classified moves._")
    return "\n".join(lines)


def main():
    con = duckdb.connect(str(DB_PATH), read_only=True)
    report = run(con)
    con.close()
    REPORT_PATH.write_text(report + "\n", encoding="utf-8")
    print(f"Audit report written to {REPORT_PATH.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
