"""CSMP Gate (a) — equity bhavcopy quality audit (report generator).

Reads only the gate-(a) store (data/market_data/equity_bhavcopy.duckdb):
  * equity_bhavcopy  — the ingested EQ/BE daily rows
  * trading_calendar — authoritative NSE trading days for the span, built by
                       ingest_equity_bhavcopy.build_trading_calendar (1m index
                       calendar for 2023+, F&O oracle for pre-2023)
  * ingest_meta      — winning source era per stored trade date
  * symbol_changes   — NSE symbol-rename inventory

The audit is therefore standalone against the store file and needs no network
and no raw download cache (F7). Numbers are derived purely from the store, so
re-runs regenerate an identical report (no wall-clock timestamps embedded).

Writes docs/reports/CSMP_GATE_A_EQUITY_BHAVCOPY_AUDIT.md.

Usage:
    python scripts/csmp/audit_equity_bhavcopy.py
"""

import sys
from datetime import date
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from scripts.csmp.ingest_equity_bhavcopy import (  # noqa: E402
    DB_PATH, SECFULL_START, UDIFF_START, LEGACY_LAST,
)

REPORT_PATH = ROOT / "docs" / "reports" / "CSMP_GATE_A_EQUITY_BHAVCOPY_AUDIT.md"

CONTINUITY_SYMBOLS = [
    "RELIANCE", "TCS", "INFY", "HDFCBANK", "ICICIBANK", "SBIN", "ITC", "LT",
    "AXISBANK", "KOTAKBANK", "HINDUNILVR", "BHARTIARTL", "MARUTI", "ASIANPAINT",
    "WIPRO", "ONGC", "NTPC", "POWERGRID", "TATAMOTORS", "SUNPHARMA",
]
CONTINUITY_TOL = 0.001  # 0.1% — larger than rounding, smaller than any CA
INTERIOR_GAP_DAYS = 14  # G3-b: the longest multi-day NSE closure in the
                        # 2010-2026 span (excluding 2-day weekends). A gap
                        # exceeding this is a missing ingest range, not a
                        # legitimate market closure.
RESTRICTED_THRESHOLD = 200  # H1: below this the day traded a narrow instrument
                            # set (e.g. gold ETFs on a festival Sunday) and is
                            # not a rankable cross-section. n_symbols == 0 is a
                            # coverage hole, not a restricted session.


def run(con):
    L = []
    w = L.append

    total = con.execute("SELECT COUNT(*) FROM equity_bhavcopy").fetchone()[0]
    if total == 0:
        w("# CSMP Gate (a) — Equity Bhavcopy Audit\n")
        w("**STORE EMPTY** — run `ingest_equity_bhavcopy.py` first.")
        return "\n".join(L)

    dmin, dmax = con.execute(
        "SELECT MIN(trade_date), MAX(trade_date) FROM equity_bhavcopy"
    ).fetchone()
    n_symbols = con.execute(
        "SELECT COUNT(DISTINCT symbol) FROM equity_bhavcopy").fetchone()[0]
    n_days = con.execute(
        "SELECT COUNT(DISTINCT trade_date) FROM equity_bhavcopy").fetchone()[0]
    store_mb = DB_PATH.stat().st_size / 1e6

    w("# CSMP Gate (a) — Equity Bhavcopy Ingestion Audit\n")
    w("*Generated by `scripts/csmp/audit_equity_bhavcopy.py` — numbers are "
      "derived from the store and are reproducible on re-run.*\n")
    w(f"- **Store:** `{DB_PATH.relative_to(ROOT).as_posix()}` "
      f"(~{store_mb:,.1f} MB — approximate; DuckDB file size varies across "
      f"rebuilds and is not part of the byte-identity guarantee, F6)")
    w(f"- **Span:** {dmin} -> {dmax}")
    w(f"- **Rows:** {total:,}  |  **Distinct symbols:** {n_symbols:,}  |  "
      f"**Distinct trade dates:** {n_days:,}")
    w("- **Series retained:** EQ, BE")
    w("")

    dev_days = con.execute(
        "SELECT COUNT(DISTINCT trade_date) FROM equity_bhavcopy "
        "WHERE trade_date BETWEEN DATE '2012-01-01' AND DATE '2022-12-31'"
    ).fetchone()[0]
    sealed_days = con.execute(
        "SELECT COUNT(DISTINCT trade_date) FROM equity_bhavcopy "
        "WHERE trade_date BETWEEN DATE '2023-01-01' AND DATE '2026-06-30'"
    ).fetchone()[0]
    # H1: the window sizes a downstream gate keys off must be full-session
    # counts. A restricted day carries no rankable cross-section.
    dev_full = con.execute(
        "SELECT COUNT(*) FROM trading_calendar WHERE trade_date BETWEEN "
        "DATE '2012-01-01' AND DATE '2022-12-31' AND n_symbols >= ?",
        [RESTRICTED_THRESHOLD]).fetchone()[0]
    sealed_full = con.execute(
        "SELECT COUNT(*) FROM trading_calendar WHERE trade_date BETWEEN "
        "DATE '2023-01-01' AND DATE '2026-06-30' AND n_symbols >= ?",
        [RESTRICTED_THRESHOLD]).fetchone()[0]
    is_slice = not (dmin <= date(2010, 12, 31) and n_days > 1000)
    if is_slice:
        w(f"> **PROOF-OF-LIFE SLICE — NOT GATE EVIDENCE.** This store holds only "
          f"{n_days} trade day(s) ({dmin} .. {dmax}); dev-window (2012–2022) "
          f"days = {dev_days}, sealed-window (2023–2026) days = {sealed_days}. "
          f"Gate (a) targets the full 2010-01-01 → present series (~4,000 "
          f"trading days). The pipeline is exercised end-to-end and the code "
          f"paths validate, but the substantive coverage / era / continuity "
          f"claims below are only meaningful after the operator's full-span "
          f"ingest. **This report cannot support a gate PASS.**\n")

    store_days = {r[0] for r in con.execute(
        "SELECT DISTINCT trade_date FROM equity_bhavcopy").fetchall()}
    cal = con.execute(
        "SELECT trade_date, source FROM trading_calendar ORDER BY trade_date"
    ).fetchall()
    cal_days = {r[0]: r[1] for r in cal}

    # === 1. Coverage ==========================================================
    w("## 1. Coverage\n")
    w("Trade days present per year vs the authoritative `trading_calendar`: "
      "the F&O-bhavcopy oracle (an independent NSE product on the identical "
      "trading calendar, probed across the whole span) plus the content-"
      "validated 1m index store (bars' own date must match the filename and "
      "carry >= 100 symbols). Any calendar day the market provably traded but "
      "the store lacks is a **source hole**, counted regardless of cause "
      "(F1/F3/G5).\n")

    years = sorted({d.year for d in store_days} | {d.year for d in cal_days})
    w("| Year | Store trade days | Calendar trade days | Missing (holes) |")
    w("|------|-----------------:|--------------------:|----------------:|")
    for y in years:
        sd = sum(1 for d in store_days if d.year == y)
        cd = sum(1 for d, s in cal_days.items()
                 if d.year == y and s != "unresolved")
        miss = sum(1 for d, s in cal_days.items()
                   if d.year == y and s != "unresolved"
                   and dmin <= d <= dmax and d not in store_days)
        w(f"| {y} | {sd} | {cd} | {miss} |")
    w("")

    # G1: calendar provenance — how much of the calendar is independently
    # corroborated vs merely the store's own dates fed back to itself.
    mix = con.execute(
        "SELECT source, COUNT(*) FROM trading_calendar GROUP BY 1 ORDER BY 1"
    ).fetchall()
    w("**Calendar source mix:** "
      + ", ".join(f"`{s}`={n:,}" for s, n in mix)
      + ". `equity_store` days are present in the store (excluded from probing "
        "— a stored day cannot be a hole by definition); `fo_probe` and "
        "`index_1m` days are independently corroborated by a source other than "
        "the equity store; `unresolved` days are transient probe failures the "
        "oracle could not adjudicate (N1 — must be resolved before PASS).\n")

    # Holes = CONFIRMED-trading calendar days absent from the store. Unresolved
    # days are NOT holes (status unknown) but block the pass (N1).
    missing = sorted(d for d, s in cal_days.items()
                     if s != "unresolved" and dmin <= d <= dmax
                     and d not in store_days)
    unresolved_days = sorted(d for d, s in cal_days.items()
                             if s == "unresolved")
    w(f"**Coverage holes within store span ({dmin}..{dmax}): "
      f"{len(missing)}**\n")
    if missing:
        w("Every row below is a day the market provably traded (per the source "
          "shown) yet is absent from the equity store — a gate-(a) failure "
          "until filled or explained.\n")
        w("| Date | Weekday | Market-open confirmed via |")
        w("|------|---------|---------------------------|")
        for d in missing:
            wd = d.strftime("%a")
            w(f"| {d} | {wd} | {cal_days[d]} |")
        w("")
        w(f"> **{len(missing)} genuine coverage hole(s).** Gate (a) is NOT fit "
          f"for purpose until each is filled or explained (charter constraint "
          f"4: report failures as failures).\n")
    else:
        w("No calendar trading day within the store span is missing from the "
          "equity store.\n")

    # H1: session breadth. The store includes days where only a thin cross-section
    # traded (gold-ETF-only festival sessions: 7 and 14 symbols). They
    # are real trading days, but they are not full equity sessions — a downstream
    # cross-sectional momentum gate must not treat them as rankable days.
    cal_with_n = con.execute(
        "SELECT trade_date, source, n_symbols FROM trading_calendar "
        "ORDER BY n_symbols NULLS FIRST"
    ).fetchall()
    restricted = [(r[0], r[2]) for r in cal_with_n
                  if r[1] != "unresolved" and r[2] is not None
                  and 0 < r[2] < RESTRICTED_THRESHOLD]
    full_cal_days = sum(1 for r in cal_with_n
                        if r[1] != "unresolved" and (r[2] is None
                        or r[2] >= RESTRICTED_THRESHOLD))
    if restricted:
        w(f"**Restricted sessions (< {RESTRICTED_THRESHOLD} symbols): "
          f"{len(restricted)}**\n")
        w("These are real NSE trading days — correctly ingested raw — but the "
          "cross-section traded only a narrow instrument set (gold ETFs on "
          "festival Sundays). For a cross-sectional momentum program, they are "
          "not rankable days. Downstream gates should key off the "
          "`trading_calendar.n_symbols` column to distinguish full sessions "
          f"(>= {RESTRICTED_THRESHOLD} symbols) from restricted ones.\n")
        w("| Date | Weekday | Symbols | Instruments traded (from the store) |")
        w("|------|---------|--------:|-------------------------------------|")
        for d, n in restricted:
            syms = [r[0] for r in con.execute(
                "SELECT symbol FROM equity_bhavcopy WHERE trade_date = ? "
                "ORDER BY symbol", [d]).fetchall()]
            shown = ", ".join(syms[:6]) + (f", … (+{len(syms) - 6})"
                                           if len(syms) > 6 else "")
            w(f"| {d} | {d.strftime('%a')} | {n} | {shown} |")
        w("")
    w(f"**Full-session trading days: {full_cal_days}** "
      f"(total calendar days {len(cal_with_n)} minus restricted "
      f"{len(restricted)} and unresolved {len(unresolved_days)})\n")

    # N1: unresolved oracle probes — absence must not read as confirmation.
    w(f"**Unresolved oracle probes: {len(unresolved_days)}**\n")
    if unresolved_days:
        w("The F&O oracle could not adjudicate these days (transient failure); "
          "they are neither confirmed trading days nor confirmed holidays, so "
          "coverage over them is UNKNOWN. Re-run the ingest to resolve (no "
          "cache marker was written, so each is re-probed).\n")
        w("| Date | Weekday |")
        w("|------|---------|")
        for d in unresolved_days[:60]:
            w(f"| {d} | {d.strftime('%a')} |")
        if len(unresolved_days) > 60:
            w(f"| … | (+{len(unresolved_days) - 60} more) |")
        w("")
        w(f"> **{len(unresolved_days)} unresolved day(s).** Gate (a) cannot PASS "
          f"while coverage over any day is unknown (N1).\n")

    # Saturday / Sunday special sessions surfaced by the calendar (F5 / G8).
    for wd_idx, label in ((5, "Saturday"), (6, "Sunday")):
        sess = sorted(d for d, s in cal_days.items()
                      if d.weekday() == wd_idx and s != "unresolved")
        if sess:
            w(f"**{label} special sessions in calendar ({len(sess)}):** "
              + ", ".join(f"{d} ({cal_days[d]}"
                          + (", in store" if d in store_days else ", MISSING")
                          + ")" for d in sess) + "\n")
        else:
            w(f"No {label} special sessions fall in this span.\n")

    worst_gap = _flag_long_gaps(w, sorted(store_days))

    # === 2. Era map ===========================================================
    w("## 2. Source / Era Map\n")
    w("Winning source per stored date (from `ingest_meta`). Delivery fields "
      "(`deliv_qty`, `deliv_pct`) exist only in the SECFULL era; LEGACY and "
      "UDIFF store them NULL.\n")
    era = con.execute("""
        SELECT m.source,
               COUNT(*)                    AS days,
               MIN(m.trade_date)           AS lo,
               MAX(m.trade_date)           AS hi
        FROM ingest_meta m GROUP BY m.source ORDER BY lo
    """).fetchall()
    deliv = con.execute("""
        SELECT m.source,
               SUM(CASE WHEN e.deliv_qty IS NOT NULL THEN 1 ELSE 0 END) AS has,
               COUNT(*) AS n
        FROM ingest_meta m JOIN equity_bhavcopy e USING (trade_date)
        GROUP BY m.source
    """).fetchall()
    deliv_by_src = {r[0]: (r[1], r[2]) for r in deliv}
    if era:
        w("| Source era | Trade days | Span | Delivery rows / total rows |")
        w("|------------|-----------:|------|---------------------------|")
        for src, days, lo, hi in era:
            has, n = deliv_by_src.get(src, (0, 0))
            w(f"| {src} | {days} | {lo}..{hi} | {has:,} / {n:,} |")
    else:
        w("*(`ingest_meta` empty — rebuild the store with the current ingest "
          "script so per-date source is recorded.)*")
    w("")
    w(f"- LEGACY window: source ends {LEGACY_LAST} (delivery never present).")
    w(f"- SECFULL window: from {SECFULL_START} (delivery present; some "
      f"BE-series rows carry '-' delivery -> stored NULL, expected).")
    w(f"- UDIFF window: fallback from {UDIFF_START} (delivery not carried). "
      f"UDIFF is a fallback that no day in this store required: SECFULL "
      f"outranks it and SECFULL is complete, so the era map shows 0 UDIFF "
      f"rows. The parser was exercised once against a live payload "
      f"(`udiff_20240703.zip` in the raw cache) and is otherwise unexercised. "
      f"The SECFULL > UDIFF > LEGACY order is structural (first-success-wins "
      f"in `ingest_day`), not empirically tested by this store (R5).")
    w("")

    # === 3. Integrity screens =================================================
    w("## 3. Integrity Screens\n")
    screens = {
        "Missing/absent OHLC (any of O/H/L/C NULL)":
            "open IS NULL OR high IS NULL OR low IS NULL OR close IS NULL",
        "Zero or negative close":
            "close IS NOT NULL AND close <= 0",
        "high < low":
            "high IS NOT NULL AND low IS NOT NULL AND high < low",
        "close outside [low, high]":
            "close IS NOT NULL AND low IS NOT NULL AND high IS NOT NULL "
            "AND (close < low OR close > high)",
        "Negative volume":
            "volume IS NOT NULL AND volume < 0",
    }
    w("| Screen | Rows flagged | Disposition |")
    w("|--------|-------------:|-------------|")
    for label, cond in screens.items():
        n = con.execute(
            f"SELECT COUNT(*) FROM equity_bhavcopy WHERE {cond}").fetchone()[0]
        disp = "none" if n == 0 else "kept-with-flag (raw preserved for gate b)"
        w(f"| {label} | {n:,} | {disp} |")
    dups = con.execute(
        "SELECT COUNT(*) FROM (SELECT trade_date, symbol, series "
        "FROM equity_bhavcopy GROUP BY 1,2,3 HAVING COUNT(*) > 1)").fetchone()[0]
    w(f"| Duplicate (trade_date, symbol, series) | {dups:,} | "
      f"impossible — enforced by PRIMARY KEY |")
    w("")

    # === 4. Cross-era continuity ==============================================
    w("## 4. Cross-Era Continuity & Corporate-Action Candidates\n")
    w(f"For {len(CONTINUITY_SYMBOLS)} long-lived liquid symbols, two checks "
      f"across the whole series (spanning the LEGACY->SECFULL boundary):\n")
    w(f"1. **`prev_close` chain integrity** — `prev_close(t)` vs `close(t-1)` "
      f"within {CONTINUITY_TOL:.1%}. NOTE: NSE publishes `prev_close` as the "
      f"**raw** prior close, so it equals `close(t-1)` *even across* splits and "
      f"bonuses (verified: RELIANCE 2017-09-07 bonus — close 1645→818 while "
      f"`prev_close`=1645.40). A non-zero count here therefore means a genuine "
      f"data glitch, not a corporate action. 0 = clean chain.\n")
    w(f"2. **Corporate-action candidates** — close-to-close moves `<= -20%` or "
      f"`>= +25%` (the gate-(b) thresholds). This is where splits/bonuses "
      f"actually surface. Reported here as a preview and handed to gate (b) for "
      f"sourcing/adjustment; **not adjusted at gate (a)**.\n")
    w("| Symbol | Rows | prev_close glitches | CA candidates (close-to-close) |")
    w("|--------|-----:|--------------------:|-------------------------------:|")
    total_glitches = 0
    total_ca = 0
    present_syms = 0
    for sym in CONTINUITY_SYMBOLS:
        rows = con.execute(
            "SELECT trade_date, close, prev_close FROM equity_bhavcopy "
            "WHERE symbol = ? AND series = 'EQ' ORDER BY trade_date", [sym]
        ).fetchall()
        if len(rows) < 2:
            continue
        present_syms += 1
        glitches = 0
        ca = 0
        for i in range(1, len(rows)):
            prev_close_t = rows[i][2]
            close_t = rows[i][1]
            close_prev = rows[i - 1][1]
            if close_prev is None or close_prev == 0:
                continue
            if (prev_close_t is not None
                    and abs(prev_close_t - close_prev) / close_prev
                    > CONTINUITY_TOL):
                glitches += 1
            if close_t is not None:
                ret = close_t / close_prev - 1.0
                if ret <= -0.20 or ret >= 0.25:
                    ca += 1
        total_glitches += glitches
        total_ca += ca
        w(f"| {sym} | {len(rows)} | {glitches} | {ca} |")
    w("")
    w(f"Totals across {present_syms} sampled symbols: **{total_glitches}** "
      f"prev_close glitches (expected 0 — the chain is intact), "
      f"**{total_ca}** corporate-action candidates surfaced for gate (b).")
    # H1 reconciliation: full-history equities appear on $full_cal_days - 2
    # restricted sessions, not all 4,099 calendar trading days. Surface the
    # per-symbol day count of a canonical symbol so the reader can reconcile §1
    # with §4.
    rel_rows = len(con.execute(
        "SELECT 1 FROM equity_bhavcopy WHERE symbol='RELIANCE' AND series='EQ'"
    ).fetchall())
    w(f"\nAll full-history equities (e.g. RELIANCE) appear on "
      f"**{rel_rows}** days — the full-session subset of the "
      f"{full_cal_days + len(restricted)}-day calendar. The "
      f"{full_cal_days + len(restricted) - rel_rows}-day difference is the "
      f"{len(restricted)} restricted sessions (§1) where those symbols did not "
      f"trade. The calendar row counts are correct; the divergence is the "
      f"session-breadth distinction H1 exists to surface.\n")

    # === 5. Symbol-rename inventory ===========================================
    w("## 5. Symbol-Rename Inventory\n")
    n_changes = con.execute("SELECT COUNT(*) FROM symbol_changes").fetchone()[0]
    if n_changes == 0:
        w("`symbol_changes` table is EMPTY. Source (NSE `symbolchange.csv`) was "
          "not obtainable this run; re-run ingestion to populate. Inventory "
          "feeding gates (b)/(c); not applied at gate (a).\n")
    else:
        rng = con.execute(
            "SELECT MIN(effective_dt), MAX(effective_dt) FROM symbol_changes"
        ).fetchone()
        w(f"`symbol_changes` populated: **{n_changes:,}** rename records "
          f"({rng[0]} .. {rng[1]}). Inventory only — not applied at gate (a); "
          f"feeds point-in-time mapping in gates (b)/(c).")
        matched = con.execute(
            "SELECT COUNT(*) FROM symbol_changes sc WHERE EXISTS ("
            "SELECT 1 FROM equity_bhavcopy e WHERE e.symbol = sc.new_symbol)"
        ).fetchone()[0]
        w(f"\nRenames whose new_symbol appears in the store: {matched:,}.\n")

    # === 6. Fit-for-purpose ===================================================
    w("## 6. Fit-for-Purpose Statement\n")
    w(f"- Coverage holes vs authoritative calendar: **{len(missing)}**")
    w(f"- Unresolved oracle probes (coverage unknown): **{len(unresolved_days)}**")
    w(f"- Full-session trading days: **{full_cal_days}**  |  "
      f"Restricted: **{len(restricted)}** (gold-ETF-only; see §1)")
    w(f"- Store span: **{dmin} -> {dmax}**")
    w(f"- Dev-window (2012–2022) full-session days: **{dev_full}** "
      f"(of {dev_days} calendar days)  |  Sealed-window (2023–2026) "
      f"full-session days: **{sealed_full}** (of {sealed_days})")
    w(f"- Largest interior gap: **{worst_gap}** days")
    w("")
    fail = []
    if is_slice:
        fail.append("PROOF-OF-LIFE ONLY — NOT A GATE PASS. Zero holes over "
                     "this slice confirms the ingest->calendar->audit pipeline "
                     "runs end-to-end and the code paths are sound, but a "
                     f"slice of {n_days} day(s) is not the gate's evidence.")
    else:
        if missing:
            fail.append(f"{len(missing)} coverage hole(s) against the "
                         "authoritative calendar (see §1)")
        if unresolved_days:
            fail.append(f"{len(unresolved_days)} unresolved oracle probe(s) "
                         "(coverage unknown — N1)")
        if worst_gap > INTERIOR_GAP_DAYS:
            fail.append(f"{worst_gap}-day interior gap > {INTERIOR_GAP_DAYS} "
                         "threshold — missing ingest range (G3-b)")
    if fail:
        w(f"**Gate (a) NOT fit for purpose:** " + "; ".join(fail) + ".")
    else:
        w("**Gate (a) can honestly claim:** a complete, deterministic, "
          "re-runnable raw EQ/BE daily store over the full target span with "
          f"**{full_cal_days} full-session trading days** (plus "
          f"**{len(restricted)} restricted gold-ETF sessions**; see §1) "
          f"and no coverage hole against the authoritative trading calendar "
          f"across the dev ({dev_full} full-session days) and sealed "
          f"({sealed_full} full-session days) "
          "windows; no unresolved oracle probe; no interior gap exceeding "
          f"{INTERIOR_GAP_DAYS} days; delivery present from the SECFULL era; "
          "corporate-action candidates catalogued (not adjusted) for gate (b); "
          "symbol-rename inventory captured; Saturday and Sunday special "
          "sessions surfaced. Prices are RAW and unadjusted by design.")
    w("")
    w("_Scope note: this gate makes no claim about corporate-action "
      "correctness (gate b), point-in-time universe membership (gate c), fees "
      "(gate d), or signal viability (gate e). The audit reads only the store "
      "tables (equity_bhavcopy, trading_calendar, ingest_meta, symbol_changes) "
      "and is standalone; the trading_calendar must be built by the ingest "
      "script (network) before this audit is meaningful._")
    return "\n".join(L)


def _flag_long_gaps(w, sorted_days):
    """Report the largest inter-day gap and return its size in days (G3-b)."""
    if len(sorted_days) < 2:
        return 0
    worst = (0, None, None)
    for i in range(1, len(sorted_days)):
        gap = (sorted_days[i] - sorted_days[i - 1]).days
        if gap > worst[0]:
            worst = (gap, sorted_days[i - 1], sorted_days[i])
    if worst[0] > INTERIOR_GAP_DAYS:
        w(f"> **INTERIOR-GAP FLAG:** contiguous gap of {worst[0]} days "
          f"({worst[1]} -> {worst[2]}) exceeds the {INTERIOR_GAP_DAYS}-day "
          f"threshold. No NSE closure is this long: this is a **missing ingest "
          f"range — a data failure until proven otherwise**. Fill the range; do "
          f"NOT move the research window to fit the gap.\n")
    else:
        w(f"Largest inter-day gap: {worst[0]} days "
          f"({worst[1]} -> {worst[2]}) — under the {INTERIOR_GAP_DAYS}-day "
          f"interior-gap threshold.\n")
    return worst[0]


def main():
    con = duckdb.connect(str(DB_PATH), read_only=True)
    report = run(con)
    con.close()
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    REPORT_PATH.write_text(report + "\n", encoding="utf-8")
    print(f"Audit report written to {REPORT_PATH.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
