"""MRLC-test forward paper scanner (EOD cadence, 1d + 1h + 4h signal tracks). DISABLED.

**`run` is refused (operator instruction 2026-09-13).** This scanner reads the
equity breadth 1m store at signal level — resampling it to 1h/4h and evaluating a
sweep/reclaim trading rule — on the surface PTMS certified the same day. It had
already consumed 2023-01-02 -> 2026-08-28 in backtest (229 symbols, four
timeframes, a parameter grid) and 2026-09-02 in forward paper; each further run
takes more of the only fresh window Family F has, and that window cannot be
regenerated by any means except waiting.

`status` and `trades` still work: they read the paper ledger, not market data.

To re-enable: an operator decision recorded in the exposure register, since a
constraint that is documented but never asserted is documentation, not a control
(CLAUDE.md, the 2026-07-31 stale-feed lesson). Deleting this guard is not by
itself authorization.

Nightly run AFTER the EOD ingests land (bhavcopy + 1m):

    python scripts/mrlc_test/scanner.py run            # detect + fill + track
    python scripts/mrlc_test/scanner.py status         # open trades + summary
    python scripts/mrlc_test/scanner.py trades         # all trades (--only open|closed)
    python scripts/mrlc_test/scanner.py run --as-of YYYY-MM-DD   # replay test

Tracks:
- 1d : daily sweep/reclaim on the bhavcopy CA-adjusted store (as before).
- 1h/4h : sweep/reclaim on 1m-store resamples (EOD-detected). Requires the 1m
  store to be fresh (gate: today's 1m file present with >= MIN_1M_SYMBOLS rows);
  otherwise the intraday tracks are skipped for the run and logged.

Fill honesty: signals detected the day they fire are PENDING and fill at the NEXT
SESSION'S OPEN (T+1 open) — a conservative degradation vs the backtest's next-bar
open, by design. Backfilled signals (older than today) use their actual next-bar
open. Exit logic is the validated engine (_simulate): 50% at the prior-day 25-SMA,
break-even then 2x ATR trail, 20-session time stop, delivery fees.

NOTE: the same symbol can signal on 1d, 1h and 4h in the same session — three
ledger rows for one market event (validation ledger; not a position cap).
"""
import sys
import argparse
from datetime import date, timedelta
from pathlib import Path

import duckdb
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from core.execution.equity.delivery_fees import delivery_equity_fees  # noqa: E402
from scripts.mrlc_test.engine import (  # noqa: E402
    run_symbol, _simulate, _crash_near, RECLAIM_MAX_BARS,
    VOL_MULT, MIN_STRETCH, SMA_DAYS, SUPPORT_SESSIONS,
)

ADJ_DB = ROOT / "data" / "market_data" / "equity_bhavcopy.duckdb"
ONE_MIN_DIR = ROOT / "data" / "market_data" / "nse" / "candles" / "1m"
PAPER_DB = ROOT / "data" / "mrlc_test" / "paper" / "paper.duckdb"
TICKERS_CSV = ROOT / "data" / "mrlc_test" / "live_tickers.csv"
LOOKBACK_DAYS = 130          # ~85 sessions, enough for SMA25 + support + guards
MIN_1M_SYMBOLS = 100         # freshness gate for the intraday tracks
TFS = ("1d", "1h", "4h")

PAPER_DB_OVERRIDE = None


def paper_db():
    return Path(PAPER_DB_OVERRIDE) if PAPER_DB_OVERRIDE else PAPER_DB


# ---------------------------------------------------------------- mapping
def build_live_tickers(force=False):
    if TICKERS_CSV.exists() and not force:
        df = pd.read_csv(TICKERS_CSV)
        return df["ticker"].tolist()
    uni = pd.read_csv(ROOT / "data" / "mrlc_test" / "universe.csv")["symbol"]
    isins = {s.split("|")[1] for s in uni}
    con = duckdb.connect(str(ADJ_DB), read_only=True)
    rows = con.execute("SELECT symbol, isin FROM symbol_isin").fetchall()
    rows += con.execute(
        "SELECT symbol, isin FROM instrument_master WHERE isin IS NOT NULL"
    ).fetchall()
    con.close()
    by_isin = {}
    for s, i in rows:
        by_isin.setdefault(i, s)
    tickers = sorted({by_isin[i] for i in isins if i in by_isin})
    pd.DataFrame({"ticker": tickers}).to_csv(TICKERS_CSV, index=False)
    print(f"live tickers: {len(tickers)} mapped (of {len(isins)} ISINs)")
    return tickers


def ticker_to_isin(tickers):
    con = duckdb.connect(str(ADJ_DB), read_only=True)
    rows = con.execute("SELECT symbol, isin FROM symbol_isin").fetchall()
    rows += con.execute(
        "SELECT symbol, isin FROM instrument_master WHERE isin IS NOT NULL"
    ).fetchall()
    con.close()
    m = {}
    for s, i in rows:
        if i and s in set(tickers):
            m[s] = i
    return m


# ---------------------------------------------------------------- ledger
def connect():
    db = paper_db()
    db.parent.mkdir(parents=True, exist_ok=True)
    con = duckdb.connect(str(db))
    cols = [r[0] for r in con.execute(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_name = 'signals'").fetchall()] if con.execute(
        "SELECT count(*) FROM information_schema.tables WHERE table_name='signals'"
    ).fetchone()[0] else []
    if cols and "tf" not in cols:
        con.execute("DROP TABLE IF EXISTS signals")
        con.execute("DROP TABLE IF EXISTS trades")
        con.execute("DROP TABLE IF EXISTS run_log")
    con.execute("""CREATE TABLE IF NOT EXISTS signals (
        signal_id INTEGER PRIMARY KEY, symbol VARCHAR, tf VARCHAR, signal_date DATE,
        stretch_pct DOUBLE, support DOUBLE, sweep_low DOUBLE, sl DOUBLE,
        tp DOUBLE, atr_sig DOUBLE, entry_date DATE, entry_price DOUBLE,
        status VARCHAR, note VARCHAR, created_at TIMESTAMP)""")
    con.execute("""CREATE TABLE IF NOT EXISTS trades (
        trade_id INTEGER PRIMARY KEY, signal_id INTEGER, symbol VARCHAR, tf VARCHAR,
        signal_date DATE, entry_date DATE, entry_price DOUBLE, sl DOUBLE,
        tp DOUBLE, atr_sig DOUBLE,
        exit1_date DATE, exit1_price DOUBLE, reason1 VARCHAR,
        exit2_date DATE, exit2_price DOUBLE, reason2 VARCHAR,
        hold_sessions INTEGER, r_gross DOUBLE, r_net DOUBLE,
        fees_rs DOUBLE, status VARCHAR)""")
    con.execute("""CREATE TABLE IF NOT EXISTS run_log (
        run_date DATE, as_of DATE, scanned INTEGER, new_signals INTEGER,
        filled INTEGER, closed INTEGER, note VARCHAR)""")
    return con


# ---------------------------------------------------------------- data
def load_recent(con, as_of):
    as_of = as_of or date.today()
    lo = (as_of - timedelta(days=LOOKBACK_DAYS)).isoformat()
    con.execute(f"ATTACH '{ADJ_DB.as_posix()}' AS adj (READ_ONLY)")
    con.execute("DROP TABLE IF EXISTS recent")
    con.execute(f"""CREATE TABLE recent AS
        SELECT trade_date, symbol, open, high, low, close, volume
        FROM adj.equity_bhavcopy_adjusted
        WHERE trade_date >= '{lo}' AND trade_date <= '{as_of.isoformat()}'""")
    con.execute("DETACH adj")


def load_1m_window(con, as_of, tk_to_isin, verbose=True):
    """Resample the 1m store's recent window into m1h/m4h/m1d (keyed by ticker).
    Returns True if the window was fresh enough to scan intraday tracks."""
    as_of = as_of or date.today()
    lo = as_of - timedelta(days=LOOKBACK_DAYS)
    files = {f.stem: f for f in ONE_MIN_DIR.glob("*.duckdb")
             if lo.isoformat() <= f.stem <= as_of.isoformat()}
    if as_of.isoformat() not in files:
        if verbose:
            print(f"  1m gate: {as_of}.duckdb missing -> intraday tracks skipped")
        return False
    isin_set = set(tk_to_isin.values())
    frames = []
    sym_count = 0
    for d in sorted(files):
        f = files[d]
        try:
            con2 = duckdb.connect(str(f), read_only=True)
            df = con2.execute(
                "SELECT symbol, timestamp, open, high, low, close, volume "
                "FROM candles WHERE symbol LIKE 'NSE_EQ|%' AND NOT is_synthetic"
            ).fetchdf()
            con2.close()
        except Exception:
            continue
        if df.empty:
            continue
        df = df[df["symbol"].str.split("|", expand=True)[1].isin(isin_set)]
        sym_count = max(sym_count, df["symbol"].nunique())
        frames.append(df)
    if sym_count < MIN_1M_SYMBOLS:
        if verbose:
            print(f"  1m gate: only {sym_count} mapped symbols on {as_of} -> intraday skipped")
        return False
    all1m = pd.concat(frames, ignore_index=True)
    all1m["ticker"] = all1m["symbol"].map({f"NSE_EQ|{i}": t for t, i in tk_to_isin.items()})
    all1m = all1m.dropna(subset=["ticker"])
    ts = pd.to_datetime(all1m["timestamp"])
    minutes = ts.dt.hour * 60 + ts.dt.minute
    ok = (minutes >= 9 * 60 + 15) & (minutes <= 15 * 60 + 30)
    df = all1m[ok].copy()
    df["date"] = ts[ok].dt.normalize()
    df["h_bucket"] = (minutes[ok] - (9 * 60 + 15)) // 60
    df["h4_bucket"] = (minutes[ok] - (9 * 60 + 15)) // 240

    def build(keys, unit):
        g = df.groupby(["ticker"] + keys, sort=True).agg(
            open=("open", "first"), high=("high", "max"), low=("low", "min"),
            close=("close", "last"), volume=("volume", "sum")).reset_index()
        g["ts"] = g["date"] + pd.to_timedelta(g[keys[-1]] * unit, unit="h") + pd.Timedelta(hours=9, minutes=15)
        return g[["ticker", "ts", "open", "high", "low", "close", "volume"]]

    con.execute("DROP TABLE IF EXISTS m1h")
    con.execute("DROP TABLE IF EXISTS m4h")
    con.execute("DROP TABLE IF EXISTS m1d")
    for t, frame in (("m1h", build(["date", "h_bucket"], 1)),
                     ("m4h", build(["date", "h4_bucket"], 4)),
                     ("m1d", df.groupby(["ticker", "date"], sort=True).agg(
                         open=("open", "first"), high=("high", "max"),
                         low=("low", "min"), close=("close", "last"),
                         volume=("volume", "sum")).reset_index().rename(columns={"date": "ts"})
                       [["ticker", "ts", "open", "high", "low", "close", "volume"]])):
        con.register("f_tmp", frame)
        con.execute(f"CREATE TABLE {t} AS SELECT * FROM f_tmp")
    if verbose:
        n = con.execute("SELECT count(*) FROM m1h").fetchone()[0]
        print(f"  1m window OK: {sym_count} symbols, {n:,} 1h bars "
              f"({lo} -> {as_of})")
    return True


def bars_for(con, tk, tf):
    if tf == "1d":
        return con.execute(
            "SELECT trade_date AS ts, open, high, low, close, volume FROM recent "
            "WHERE symbol = ? ORDER BY trade_date", [tk]).fetchdf()
    table = {"1h": "m1h", "4h": "m4h"}[tf]
    return con.execute(
        f"SELECT ts, open, high, low, close, volume FROM {table} "
        f"WHERE ticker = ? ORDER BY ts", [tk]).fetchdf()


def daily_for(con, tk, tf):
    if tf == "1d":
        return bars_for(con, tk, "1d")
    return con.execute(
        "SELECT ts, open, high, low, close, volume FROM m1d WHERE ticker = ? ORDER BY ts",
        [tk]).fetchdf()


# ---------------------------------------------------------------- detect
def detect_last_bar_signal(bars, daily):
    """Signal whose reclaim bar is the FINAL bar of the window (entry bar does not exist yet)."""
    if len(bars) < 30:
        return []
    close = bars["close"].to_numpy()
    low = bars["low"].to_numpy()
    volume = bars["volume"].to_numpy()
    n = len(bars)
    daily_close = daily["close"].to_numpy()
    ranks = [int(r) if not pd.isna(r) else None for r in
             pd.to_datetime(bars["ts"].dt.date).map(
                 {d: r for r, d in enumerate(pd.to_datetime(daily["ts"].dt.date))}).to_numpy()]
    daily_ret = np.full(len(daily_close), np.nan)
    with np.errstate(divide="ignore", invalid="ignore"):
        daily_ret[1:] = np.diff(daily_close) / daily_close[:-1]
    j = n - 1
    rj = ranks[j]
    if rj is None or rj < max(SMA_DAYS, SUPPORT_SESSIONS):
        return []
    sma = float(daily_close[rj - SMA_DAYS:rj].mean())
    if np.isnan(sma):
        return []
    div = (close[j] - sma) / sma
    if div > -MIN_STRETCH or _crash_near(daily_ret, rj):
        return []
    mask = np.array([r is not None and r >= rj - SUPPORT_SESSIONS for r in ranks[:j]])
    if not mask.any():
        return []
    sup = float(low[:j][mask].min())
    for k in range(1, RECLAIM_MAX_BARS + 1):
        i = j - k
        if i < 0:
            break
        ri = ranks[i]
        if ri is None:
            continue
        mask_i = np.array([r is not None and r >= ri - SUPPORT_SESSIONS for r in ranks[:i]])
        if not mask_i.any():
            continue
        sup_i = float(low[:i][mask_i].min())
        med_i = pd.Series(volume[:i]).rolling(20, min_periods=20).median().iloc[-1]
        if np.isnan(med_i):
            continue
        if (close[i] < sup_i and low[i] < sup_i
                and volume[i] >= VOL_MULT * med_i and close[j] > sup_i):
            sweep_low = float(low[i:j + 1].min())
            atr = _atr14(bars).to_numpy()[j]
            if np.isnan(atr):
                return []
            return [dict(signal_date=pd.to_datetime(bars["ts"].iloc[j]).date(),
                         stretch_pct=div * 100, support=sup_i, sweep_low=sweep_low,
                         sl=sweep_low - 2.0 * atr, tp=sma, atr_sig=atr)]
    return []


def _atr14(bars):
    tr = pd.concat([
        bars["high"] - bars["low"],
        (bars["high"] - bars["close"].shift(1)).abs(),
        (bars["low"] - bars["close"].shift(1)).abs(),
    ], axis=1).max(axis=1)
    return tr.ewm(alpha=1.0 / 14, min_periods=14, adjust=False).mean()


# ---------------------------------------------------------------- pipeline
def run_pipeline(as_of=None, verbose=True):
    raise SystemExit(
        "REFUSED: the MRLC forward paper scanner is DISABLED (operator instruction\n"
        "2026-09-13).\n\n"
        "It makes signal-level reads of the equity breadth 1m store - the surface\n"
        "certified for PTMS on 2026-09-13 (Nifty 100, 2023-01-02 -> 2026-09-11).\n"
        "Its backtest already consumed 2023-01-02 -> 2026-08-28 across 229 symbols\n"
        "and its paper run reached 2026-09-02, so every further run destroys research\n"
        "budget that only calendar time can replace.\n\n"
        "Read-only ledger commands still work: scanner.py status / scanner.py trades.\n"
        "See docs/reports/index_research/PTMS_P3_WINDOW_RECONCILIATION_2026-09-13.md §2.\n"
        "Deleting this guard is not by itself authorization."
    )


def _run_pipeline_disabled(as_of=None, verbose=True):
    as_of = as_of or date.today()
    con = connect()
    load_recent(con, as_of)
    tickers = build_live_tickers()
    tk_to_isin = ticker_to_isin(tickers)
    m1_ok = load_1m_window(con, as_of, tk_to_isin, verbose)

    existing = set()
    for table in ("signals", "trades"):
        n = con.execute(f"SELECT count(*) FROM {table}").fetchone()[0]
        if n:
            existing |= {r[0] for r in con.execute(
                f"SELECT symbol || '|' || tf || '|' || signal_date FROM {table}"
            ).fetchall()}

    new_signals = scanned = 0
    skipped = [0]

    for tf in TFS:
        if tf != "1d" and not m1_ok:
            continue
        for tk in tickers:
            bars = bars_for(con, tk, tf)
            if len(bars) < 30:
                continue
            daily = daily_for(con, tk, tf)
            scanned += 1
            if con.execute(
                "SELECT count(*) FROM trades WHERE symbol = ? AND tf = ? AND status = 'OPEN'",
                [tk, tf]).fetchone()[0] > 0:
                continue

            found = run_symbol(bars, daily, 2.0, tk, tf, news_guard=True,
                               skipped_counter=skipped)
            for tr in found:
                sig_d = pd.Timestamp(tr["signal_date"]).date()
                key = f"{tk}|{tf}|{sig_d}"
                if key in existing:
                    continue
                existing.add(key)
                if sig_d == as_of:
                    _insert_signal(con, tk, tf, tr, "PENDING_ENTRY")
                    new_signals += 1
                    if verbose:
                        print(f"  SIGNAL {tf} {tk} {sig_d} div={tr['divergence_pct']:.1f}% "
                              f"-> PENDING_ENTRY (fill at next open)")
                else:
                    if tr["reason1"] == "OPEN_END" or tr["reason2"] == "OPEN_END":
                        _save_trade(con, tk, tf, tr, "OPEN")
                    else:
                        _save_trade(con, tk, tf, tr, "CLOSED")
                    new_signals += 1
                    if verbose:
                        print(f"  SIGNAL {tf} {tk} {sig_d} div={tr['divergence_pct']:.1f}% "
                              f"-> backfill {'OPEN' if tr['reason1'] == 'OPEN_END' else 'CLOSED'}")

            last = detect_last_bar_signal(bars, daily)
            for sig in last:
                key = f"{tk}|{tf}|{sig['signal_date']}"
                if key in existing:
                    continue
                existing.add(key)
                _insert_signal(con, tk, tf, sig, "PENDING_ENTRY")
                new_signals += 1
                if verbose:
                    print(f"  SIGNAL {tf} {tk} {sig['signal_date']} "
                          f"div={sig['stretch_pct']:.1f}% -> PENDING_ENTRY (fill at next open)")

    closed = _fill_and_track(con, verbose)
    tfs_run = ",".join(t for t in TFS if t == "1d" or m1_ok)
    note = f"tfs={tfs_run}" + ("" if m1_ok else "; 1m gate FAILED")
    con.execute("INSERT INTO run_log VALUES (?, ?, ?, ?, ?, ?, ?)",
                [date.today(), as_of, scanned, new_signals, 0, closed, note])
    print(f"run @ {as_of}: scanned {scanned}, {new_signals} new signals, "
          f"{closed} closed [{note}]")
    con.close()


def _insert_signal(con, tk, tf, sig, status):
    sid = con.execute("SELECT COALESCE(MAX(signal_id), 0) + 1 FROM signals").fetchone()[0]
    con.execute("INSERT INTO signals VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
                [sid, tk, tf, sig["signal_date"], sig["stretch_pct"], sig["support"],
                 sig["sweep_low"], sig["sl"], sig["tp"], sig["atr_sig"],
                 None, None, status, "", pd.Timestamp.now()])
    return sid


def _fill_and_track(con, verbose):
    closed = 0
    pending = con.execute(
        "SELECT signal_id, symbol, tf, signal_date FROM signals WHERE status = 'PENDING_ENTRY'"
    ).fetchall()
    for sid, tk, tf, sig_date in pending:
        if con.execute(
            "SELECT count(*) FROM trades WHERE symbol = ? AND tf = ? AND status = 'OPEN'",
            [tk, tf]).fetchone()[0] > 0:
            con.execute("UPDATE signals SET status = 'SKIPPED_OVERLAP' "
                        "WHERE signal_id = ?", [sid])
            continue
        bars = bars_for(con, tk, tf)
        daily = daily_for(con, tk, tf)
        sig_date = pd.Timestamp(sig_date)
        dates = pd.to_datetime(daily["ts"].dt.date).tolist()
        if not any(d > sig_date for d in dates):
            continue
        nxt = min(d for d in dates if d > sig_date)
        day_bars = bars[pd.to_datetime(bars["ts"].dt.date) == nxt]
        if day_bars.empty:
            continue
        entry = float(day_bars["open"].iloc[0])
        if entry <= 0:
            continue
        idx = bars.index.get_loc(day_bars.index[0])
        ranks = [int(r) if not pd.isna(r) else None for r in
                 pd.to_datetime(bars["ts"].dt.date).map(
                     {d: r for r, d in enumerate(pd.to_datetime(daily["ts"].dt.date))}).to_numpy()]
        rank_to_date = {r: daily["ts"].iloc[r] for r in range(len(daily))}
        row = con.execute("SELECT * FROM signals WHERE signal_id = ?", [sid]).fetchone()
        rec, _ = _simulate(bars, ranks, rank_to_date, daily, entry, row[7], row[8],
                           row[9], idx, tk, tf, row[4] / 100.0, 2.0,
                           row[6], row[5], daily["ts"].iloc[ranks[idx - 1]]
                           if idx - 1 >= 0 else daily["ts"].iloc[0])
        con.execute("UPDATE signals SET entry_date = ?, entry_price = ?, status = 'OPEN' "
                    "WHERE signal_id = ?", [daily["ts"].iloc[ranks[idx]].date(), entry, sid])
        _save_trade(con, tk, tf, rec, "OPEN")
        if verbose:
            print(f"  FILL {tf} {tk} entry {entry:.2f} on "
                  f"{daily['ts'].iloc[ranks[idx]].date()}")

    open_rows = con.execute(
        "SELECT trade_id, symbol, tf FROM trades WHERE status = 'OPEN'").fetchall()
    for tid, tk, tf in open_rows:
        bars = bars_for(con, tk, tf)
        daily = daily_for(con, tk, tf)
        row = con.execute(
            "SELECT signal_id, signal_date, entry_price, sl, tp, atr_sig, entry_date "
            "FROM trades WHERE trade_id = ?", [tid]).fetchone()
        entry_dt = pd.Timestamp(row[6])
        day_mask = pd.to_datetime(bars["ts"].dt.date) == entry_dt
        if not day_mask.any():
            continue
        idx = bars.index[day_mask][0]
        ranks = [int(r) if not pd.isna(r) else None for r in
                 pd.to_datetime(bars["ts"].dt.date).map(
                     {d: r for r, d in enumerate(pd.to_datetime(daily["ts"].dt.date))}).to_numpy()]
        rank_to_date = {r: daily["ts"].iloc[r] for r in range(len(daily))}
        rec, _ = _simulate(bars, ranks, rank_to_date, daily, row[2], row[3], row[4],
                           row[5], idx, tk, tf, 0.0, 2.0, 0.0, 0.0,
                           pd.Timestamp(row[1]))
        if rec["reason1"] != "OPEN_END" and rec["reason2"] != "OPEN_END":
            _save_trade(con, tk, tf, rec, "CLOSED")
            closed += 1
            if verbose:
                print(f"  CLOSE {tf} {tk} entry {row[2]:.2f} -> "
                      f"{rec['reason1']}/{rec['reason2']} r_net {rec['r_net']:.2f}")
    return closed


def _save_trade(con, tk, tf, rec, status):
    entry_d = pd.Timestamp(rec["entry_date"]).date() if rec["entry_date"] is not None else None
    sig_d = pd.Timestamp(rec["signal_date"]).date() if rec["signal_date"] is not None else None
    if status == "CLOSED":
        row = con.execute(
            "SELECT trade_id FROM trades WHERE symbol = ? AND tf = ? AND signal_date = ? "
            "AND status = 'OPEN'",
            [tk, tf, sig_d]).fetchone()
        if row:
            con.execute(
                "UPDATE trades SET exit1_date = ?, exit1_price = ?, reason1 = ?, "
                "exit2_date = ?, exit2_price = ?, reason2 = ?, hold_sessions = ?, "
                "r_gross = ?, r_net = ?, fees_rs = ?, status = 'CLOSED' "
                "WHERE trade_id = ?",
                [pd.Timestamp(rec["exit1_date"]).date() if rec["exit1_date"] is not None else None,
                 rec["exit1_price"], rec["reason1"],
                 pd.Timestamp(rec["exit2_date"]).date() if rec["exit2_date"] is not None else None,
                 rec["exit2_price"], rec["reason2"], rec["hold_sessions"],
                 rec["r_gross"], rec["r_net"], rec["fees_rs"], row[0]])
            return
    tid = con.execute("SELECT COALESCE(MAX(trade_id), 0) + 1 FROM trades").fetchone()[0]
    con.execute(
        "INSERT INTO trades VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",
        [tid, rec.get("signal_id", 0), tk, tf, sig_d, entry_d,
         rec["entry"], rec["sl"], rec["tp"], rec["atr_sig"],
         pd.Timestamp(rec["exit1_date"]).date() if rec["exit1_date"] is not None else None,
         rec["exit1_price"], rec["reason1"],
         pd.Timestamp(rec["exit2_date"]).date() if rec["exit2_date"] is not None else None,
         rec["exit2_price"], rec["reason2"], rec["hold_sessions"],
         rec["r_gross"], rec["r_net"], rec["fees_rs"], status])


def status():
    con = connect()
    n_sig = con.execute("SELECT count(*) FROM signals").fetchone()[0]
    print(f"signals: {n_sig}")
    for tf in TFS:
        open_ = con.execute(
            "SELECT symbol, entry_date, entry_price, sl, tp FROM trades "
            "WHERE tf = ? AND status = 'OPEN'", [tf]).fetchall()
        hist = con.execute(
            "SELECT count(*), sum(r_net), avg(r_net) FROM trades "
            "WHERE tf = ? AND status = 'CLOSED'", [tf]).fetchone()
        h = f"closed {hist[0]}, net R {hist[1]:.2f}, avg {hist[2]:.2f}" if hist[0] else "no closed"
        print(f"  [{tf}] open: {len(open_)} | {h}")
        for r in open_[:8]:
            print(f"     OPEN {r[0]} entry {r[1]} @ {r[2]:.2f} sl {r[3]:.2f} tp {r[4]:.2f}")
        if len(open_) > 8:
            print(f"     ... and {len(open_) - 8} more")
    con.close()


def trades_cmd(only="all"):
    con = connect()
    where = {"open": "WHERE status = 'OPEN'", "closed": "WHERE status = 'CLOSED'"}.get(only, "")
    df = con.execute(
        f"SELECT tf, symbol, signal_date, entry_date, entry_price AS entry, "
        f"sl, tp, exit1_date, exit1_price, reason1, exit2_date, exit2_price, "
        f"reason2, hold_sessions, r_net, fees_rs, status "
        f"FROM trades {where} ORDER BY signal_date, tf, symbol").fetchdf()
    con.close()
    if df.empty:
        print(f"no {only} trades")
        return
    pd.set_option("display.width", 200)
    pd.set_option("display.max_columns", 30)
    print(df.to_string(index=False))


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("cmd", choices=["run", "status", "trades"])
    ap.add_argument("--as-of")
    ap.add_argument("--db")
    ap.add_argument("--only", choices=["all", "open", "closed"], default="all")
    args = ap.parse_args()
    if args.db:
        PAPER_DB_OVERRIDE = args.db
    if args.cmd == "run":
        as_of = date.fromisoformat(args.as_of) if args.as_of else None
        run_pipeline(as_of)
    elif args.cmd == "status":
        status()
    else:
        trades_cmd(args.only)
