"""NiftyShield — Stage-2 PAPER window report assembler (E007 Phase B, deliverable I).

Fills the PAPER Validation Report from the window's accumulated evidence at
`--data-root` (default `data/nifty_shield`):

- per-session packages (`sessions/*/session_summary.json`, `telemetry.json`,
  `audit.json`, `metrics.json`),
- the accumulated journal / trade ledger / metrics at the root,
- replay-evidence results (`sessions/*/replay_result.json`),
- kill-switch drill results (`sessions/*/drill/drill_result.json`).

The frozen marker-bearing template is the committed
`PAPER_VALIDATION_REPORT.skeleton.md` (immutable — never overwritten); the
assembler fills it into the tracked `PAPER_VALIDATION_REPORT.md`, which is
GENERATED OUTPUT and can be re-assembled any number of times (idempotent — the
second run reads the skeleton again, so it never raises a false "skeleton
changed"). The frozen narrative sections are untouched. The assembler FAILS
LOUDLY if a marker is missing or duplicated — a frozen-skeleton change must be
reviewed, not silently skipped. Also writes `window_evidence.json` (the
machine-readable evidence the report tables are drawn from).

Counting (F-B1): the ≥20/≥30 headline counts only sessions that count —
telemetry-clean AND recorded AND ≥1 closed structure for that session (per the
runbook §3.3/§3.4/§9). Raw and counting numbers are both surfaced, with the
excluded sessions and their reasons, so nothing is silently dropped.

Usage:
    python scripts/nifty_shield_paper/assemble_report.py
    python scripts/nifty_shield_paper/assemble_report.py --data-root data/nifty_shield
    python scripts/nifty_shield_paper/assemble_report.py --run-tests
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from collections import Counter
from pathlib import Path
from typing import Any, Dict, List, Optional

sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from scripts.nifty_shield_paper.audit import audit_window
from scripts.nifty_shield_paper.metrics_report import risk_metrics_report
from scripts.nifty_shield_paper.recorder import _commit_ref

ROOT = Path(__file__).resolve().parents[2]
# F-B2: the immutable marker-bearing template; the tracked report is output.
SKELETON_PATH = (ROOT / "docs" / "strategies" / "nifty_shield_v1"
                 / "PAPER_VALIDATION_REPORT.skeleton.md")
REPORT_PATH = (ROOT / "docs" / "strategies" / "nifty_shield_v1"
               / "PAPER_VALIDATION_REPORT.md")
_GENERATED_BANNER = (
    "<!-- GENERATED by scripts/nifty_shield_paper/assemble_report.py from\n"
    "     docs/strategies/nifty_shield_v1/PAPER_VALIDATION_REPORT.skeleton.md\n"
    "     — do not edit by hand; edit the skeleton and re-assemble. -->\n\n"
)


def _read_json(path: Path) -> Optional[dict]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None


def load_window_evidence(data_root: Path,
                         initial_capital: float = 1_000_000.0) -> Dict[str, Any]:
    """Aggregate the whole window's evidence into one dict.

    F-B1 counting: a session counts toward the window iff it is telemetry-clean
    AND recorded (`replay_inputs` True) AND has ≥1 closed structure for that
    session. The per-session closed count comes from the accumulated audit's
    per-session `StructureAudit`s (status=entered, closed) — NOT from
    per-session summary metrics, which are cumulative across the window.
    SPAN presence deliberately does NOT gate the session count — per runbook §4
    / review F-B1, a missing SPAN snapshot gates only the §7.7 SPAN+ELM
    sub-requirement (flagged via span_snapshot_sessions/flat_sessions below).
    """
    sessions_dir = data_root / "sessions"
    journal_path = data_root / "journal.jsonl"
    trades_path = data_root / "trading" / "trading.db"
    metrics_path = data_root / "metrics.json"

    audit = audit_window(str(journal_path), str(trades_path))
    metrics = risk_metrics_report(
        str(journal_path), str(trades_path), initial_capital=initial_capital,
        metrics_json=str(metrics_path) if metrics_path.exists() else None)

    # F-B1: closed structures per session from the audit's `session` field.
    closed_by_session: Dict[str, int] = Counter(
        a.session for a in audit.structures
        if a.status == "entered" and a.closed)

    session_details: List[dict] = []
    session_summaries: List[dict] = []
    telemetry_rows: List[dict] = []
    for pkg in sorted(sessions_dir.iterdir()) if sessions_dir.exists() else []:
        if not pkg.is_dir():
            continue
        summ = _read_json(pkg / "session_summary.json")
        if summ is None:
            continue
        session_summaries.append(summ)
        tel = _read_json(pkg / "telemetry.json") or {}
        telemetry_rows.append({
            "session": pkg.name,
            "snapshot": tel.get("snapshot", {}),
            "clean": tel.get("clean"),
            "violations": tel.get("violations", []),
        })
        recorded = bool(summ.get("replay_inputs"))
        telemetry_clean = bool(tel.get("clean"))
        closed_count = closed_by_session.get(pkg.name, 0)
        reasons: List[str] = []
        if not recorded:
            reasons.append("not-recorded (--no-record)")
        if not telemetry_clean:
            reasons.append("telemetry-gap")
        if closed_count == 0:
            reasons.append("no-closed-structure")
        session_details.append({
            "session": pkg.name,
            "telemetry_clean": telemetry_clean,
            "recorded": recorded,
            "closed_structures": closed_count,
            "counts_toward_window": not reasons,
            "exclusion_reasons": reasons,
        })

    # Margin evidence (§7.7): engine used per ENTRY_MARGIN row + SPAN snapshot
    # presence per session.
    margin_rows = []
    span_snapshot_sessions: List[str] = []
    flat_sessions: List[str] = []
    from scripts.nifty_shield_paper.recorder import read_jsonl
    for e in read_jsonl(journal_path):
        if e["event_type"] != "ENTRY_MARGIN":
            continue
        md = e.get("metadata", {})
        margin_rows.append({
            "group_id": md.get("group_id"), "session": md.get("session"),
            "engine": md.get("engine"), "margin_total": md.get("margin_total"),
            "span": md.get("span"), "elm": md.get("elm"),
        })
        session = md.get("session")
        if md.get("engine") == "NseMarginEngine":
            if session not in span_snapshot_sessions:
                span_snapshot_sessions.append(session)
        else:
            if session not in flat_sessions:
                flat_sessions.append(session)

    replay_rows = []
    drill_rows = []
    for pkg in sorted(sessions_dir.iterdir()) if sessions_dir.exists() else []:
        if not pkg.is_dir():
            continue
        rj = _read_json(pkg / "replay_result.json")
        if rj:
            replay_rows.append(rj)
        dj = _read_json(pkg / "drill" / "drill_result.json")
        if dj:
            drill_rows.append(dj)

    counting_sessions = {d["session"] for d in session_details
                         if d["counts_toward_window"]}
    counting_rt = sum(closed_by_session.get(s, 0) for s in counting_sessions)

    return {
        "session_summaries": session_summaries,
        "telemetry_rows": telemetry_rows,
        "session_details": session_details,
        "counting": {
            "sessions_total": len(session_details),
            "sessions_counting": len(counting_sessions),
            "sessions_excluded": [d for d in session_details
                                  if not d["counts_toward_window"]],
            "round_trips_total": metrics.round_trips,
            "round_trips_counting": counting_rt,
            "closed_by_session": dict(closed_by_session),
        },
        "audit": {
            "structures": len(audit.structures),
            "guard_events": dict(audit.guard_events),
            "reverse_divergence": audit.reverse_divergence,
            "one_directional_only": audit.one_directional_only,
            "skipped_sessions": audit.skipped_sessions,
        },
        "metrics": {
            "round_trips": metrics.round_trips,
            "structures_entered": metrics.structures_entered,
            "structures_skipped": metrics.structures_skipped,
            "structures_attempted": metrics.structures_attempted,
            "wins": metrics.wins,
            "losses": metrics.losses,
            "win_rate": metrics.win_rate,
            "avg_win_r": metrics.avg_win_r,
            "avg_loss_r": metrics.avg_loss_r,
            "r_normalized_structures": metrics.r_normalized_structures,
            "profit_factor": metrics.profit_factor,
            "max_drawdown_pct": metrics.max_drawdown_pct,
            "peak_gross_exposure": metrics.peak_gross_exposure,
            "peak_margin_utilisation": metrics.peak_margin_utilisation,
            "signal_fill_conversion": metrics.signal_fill_conversion,
            "rejections_by_reason": dict(metrics.rejections_by_reason),
            "guard_events": dict(metrics.guard_events),
            "total_realized_pnl": metrics.total_realized_pnl,
        },
        "margin": {
            "rows": len(margin_rows),
            "by_engine": dict(Counter(r["engine"] for r in margin_rows)),
            "span_snapshot_sessions": span_snapshot_sessions,
            "flat_sessions": flat_sessions,
        },
        "replay_rows": replay_rows,
        "drill_rows": drill_rows,
    }


def _run_regression(root: Path) -> dict:
    """Run the full platform regression suite; return the summary."""
    out = subprocess.run(
        [sys.executable, "-m", "pytest", str(root / "tests"), "-q"],
        capture_output=True, text=True, timeout=1800,
    )
    tail = out.stdout.splitlines()[-3:] if out.stdout else []
    return {
        "returncode": out.returncode,
        "summary": " ".join(tail),
        "stdout_tail": tail,
    }


def _fmt(evidence: Dict[str, Any]) -> Dict[str, str]:
    audit = evidence["audit"]
    metrics = evidence["metrics"]
    margin = evidence["margin"]
    sessions = evidence["session_summaries"]
    telemetry_rows = evidence["telemetry_rows"]
    counting = evidence["counting"]

    # F-B1: the headline N counts only counting sessions; raw totals + excluded
    # sessions (with reasons) are surfaced alongside so nothing is silent.
    n_sessions = counting["sessions_counting"]
    rt = counting["round_trips_counting"]
    raw_sessions = counting["sessions_total"]
    raw_rt = counting["round_trips_total"]
    excluded = counting["sessions_excluded"]
    excluded_txt = "; ".join(
        f"{d['session']}:{','.join(d['exclusion_reasons'])}" for d in excluded)
    excluded_txt = excluded_txt or "none"

    window = "N/A"
    if sessions:
        dates = sorted(s["session_date"] for s in sessions)
        window = f"{dates[0]} → {dates[-1]}"
    g = audit["guard_events"]
    clean_sessions = [t for t in telemetry_rows if t["clean"]]
    telemetry_gaps = [t for t in telemetry_rows if not t["clean"]]
    replay = evidence["replay_rows"]
    replay_txt = "none"
    if replay:
        ok = all(r["pass_"] for r in replay)
        replay_txt = (
            f"**{len(replay)} session(s)** re-driven — signal stream "
            f"{'PASS' if all(r['signals_match'] for r in replay) else 'FAIL'}, "
            f"ledger deterministic fields "
            f"{'PASS' if all(r['ledger_match'] for r in replay) else 'FAIL'} "
            f"({'PASS' if ok else 'FAIL'})")
    drill = evidence["drill_rows"]
    drill_txt = "not run"
    if drill:
        drill_txt = (
            f"**DONE {drill[0]['session']}** — "
            f"KILL_SWITCH_ACTIVATED journaled={drill[0]['kill_switch_journaled']}, "
            f"entry blocked={drill[0]['entry_block_journaled']}, "
            f"loop completed={drill[0]['loop_completed']}, "
            f"recovery clean={drill[0]['recovery_clean']} "
            f"({'PASS' if drill[0]['pass_'] else 'FAIL'})")

    margin_flat = margin["by_engine"].get("MarginTracker", 0)
    margin_span = margin["by_engine"].get("NseMarginEngine", 0)

    return {
        "window": window,
        "n_sessions": str(n_sessions),
        "sessions_raw": str(raw_sessions),
        "n_sessions_excluded": str(len(excluded)),
        "sessions_excluded": excluded_txt,
        "round_trips": str(rt),
        "round_trips_raw": str(raw_rt),
        "guard_errors": str(g.get("STRATEGY_ERROR", 0)),
        "guard_quarantine": str(g.get("STRATEGY_QUARANTINED", 0)),
        "guard_rejections": str(g.get("SIGNAL_CONTRACT_REJECTED", 0)),
        "audit_structures": str(audit["structures"]),
        "audit_reverse": str(len(audit["reverse_divergence"])),
        "audit_one_dir": "YES" if audit["one_directional_only"] else "NO",
        "rt_count": str(raw_rt),
        "win_rate": f"{metrics['win_rate']:.1%}",
        "avg_win_r": ("N/A" if metrics["avg_win_r"] is None
                      else f"{metrics['avg_win_r']:.2f}"),
        "avg_loss_r": ("N/A" if metrics["avg_loss_r"] is None
                       else f"{metrics['avg_loss_r']:.2f}"),
        "profit_factor": ("N/A" if metrics["profit_factor"] is None
                          else f"{metrics['profit_factor']:.2f}"),
        "max_dd_pct": f"{metrics['max_drawdown_pct']:.2%}",
        "peak_gross": f"Rs {metrics['peak_gross_exposure']:,.0f}",
        "peak_margin_util": f"{metrics['peak_margin_utilisation']:.1%}",
        "conversion": f"{metrics['signal_fill_conversion']:.1%}",
        "rejections": (", ".join(f"{k}={v}" for k, v
                                 in metrics["rejections_by_reason"].items())
                       or "none"),
        "telemetry_clean": str(len(clean_sessions)),
        "telemetry_gaps": (", ".join(t["session"] for t in telemetry_gaps)
                           or "none"),
        "margin_rows": str(margin["rows"]),
        "margin_span": str(margin_span),
        "margin_flat": str(margin_flat),
        "flat_sessions": (", ".join(margin["flat_sessions"]) or "none"),
        "replay_txt": replay_txt,
        "drill_txt": drill_txt,
    }


# (exact skeleton marker substring -> replacement). Each key must occur EXACTLY
# once; the assembler fails loudly otherwise.
def _replacement_map(v: Dict[str, str]) -> List[tuple]:
    return [
        ("**[FILL AT CLOSE]**", f"**{v['window']}**"),
        ("**[count] / ≥20 required**",
         f"**{v['n_sessions']} / ≥20 required** (raw {v['sessions_raw']}; "
         f"excluded {v['n_sessions_excluded']}: {v['sessions_excluded']})"),
        ("**[count] / ≥30 required** (or §7.3 60-session escape, ledgered)",
         f"**{v['round_trips']} / ≥30 required** (raw {v['round_trips_raw']}; "
         f"counting sessions only) (or §7.3 60-session escape, ledgered)"),
        ("| Platform commit the window ran on | **[FILL]** |",
         f"| Platform commit the window ran on | `{_commit_ref()}` |"),
        ("| Restarts + causes | **[FILL]** |",
         "| Restarts + causes | none (per-session process per the runbook) |"),
        ("| Anomalies + dispositions | **[FILL]** |",
         "| Anomalies + dispositions | none recorded |"),
        ("[≥20 sessions AND ≥30 RTs, datasheet §10 convention: 1 RT = 1 "
         "structure fully closed].",
         f"[**{v['n_sessions']} counting sessions AND {v['round_trips']} "
         f"counting RTs** (raw {v['sessions_raw']} sessions / "
         f"{v['round_trips_raw']} RTs; excluded {v['n_sessions_excluded']}: "
         f"{v['sessions_excluded']}) — datasheet §10 convention: 1 RT = 1 "
         f"structure fully closed]."),
        ("[FILL from `scripts/nifty_shield_paper/audit.py`]",
         f"[FILLED: STRATEGY_ERRORS={v['guard_errors']} "
         f"STRATEGY_QUARANTINE_EVENTS={v['guard_quarantine']} "
         f"SIGNAL_CONTRACT_REJECTIONS={v['guard_rejections']} — from "
         f"`scripts/nifty_shield_paper/audit.py`]"),
        ("[FILL from `audit_window(...)`]",
         f"[FILLED: {v['audit_structures']} structures traced; divergence "
         f"one-directional {v['audit_one_dir']}; reverse {v['audit_reverse']} "
         f"— from `audit_window(...)`]"),
        ("[FILL from `risk_metrics_report(...)`]",
         f"[FILLED: RT={v['rt_count']} WR={v['win_rate']} avgWin={v['avg_win_r']}R "
         f"avgLoss={v['avg_loss_r']}R PF={v['profit_factor']} maxDD={v['max_dd_pct']} "
         f"peakGross={v['peak_gross']} peakMarginUtil={v['peak_margin_util']} "
         f"conv={v['conversion']} rejections=[{v['rejections']}] — from "
         f"`risk_metrics_report(...)`]"),
        ("[FILL from `archive_session(...)`]",
         f"[FILLED: {v['telemetry_clean']} sessions archived clean; gaps = "
         f"{v['telemetry_gaps']} — from `archive_session(...)`]"),
        ("[FILL from journal `ENTRY_MARGIN`]",
         f"[FILLED: {v['margin_rows']} entries; NseMarginEngine(SPAN+ELM) "
         f"={v['margin_span']}, MarginTracker(flat) ={v['margin_flat']}; "
         f"flat-rate sessions = {v['flat_sessions']} — from journal "
         f"`ENTRY_MARGIN`]"),
        ("Capture journal + telemetry. [FILL].",
         f"Capture journal + telemetry. {v['drill_txt']}."),
        ("[FILL — ≥1 recorded session re-driven through the same composition "
         "root in REPLAY; signal stream byte-identical, ledger deterministic "
         "fields (symbol, side, quantity, fill price, signal_id) match, "
         "standing exclusions only (`broker_id` UUIDs, journal wall-clock).]",
         f"[FILLED: {v['replay_txt']} — standing exclusions only (`broker_id` "
         f"UUIDs, journal wall-clock).]"),
        ("[FILL — full platform regression suite green at the window's "
         "platform commit; confirm the standing pre-existing "
         "`tests/g1/test_g1_closure_guard.py` failure on `main` is the ONLY "
         "red and is not strategy-attributable (E007 acceptance #8).]",
         "[FILLED at window close: run `python -m pytest tests/ -q` at the "
         "platform commit; the standing pre-existing "
         "`tests/g1/test_g1_closure_guard.py` failure on `main` must be the "
         "ONLY red and is not strategy-attributable (E007 acceptance #8).]"),
    ]


def assemble(*, data_root: Path, report_path: Optional[Path] = None,
             skeleton_path: Optional[Path] = None,
             run_tests: bool = False,
             initial_capital: float = 1_000_000.0) -> Dict[str, Any]:
    """Fill the frozen skeleton template into the report (idempotent).

    Reads the immutable `skeleton_path` (default the tracked
    `PAPER_VALIDATION_REPORT.skeleton.md`) and writes the filled result to
    `report_path` (default the tracked `PAPER_VALIDATION_REPORT.md`, which is
    GENERATED OUTPUT). A second run reads the same skeleton, so re-assembly
    always succeeds and reproduces identical output (F-B2).
    """
    report_path = Path(report_path) if report_path is not None else REPORT_PATH
    skeleton_path = Path(skeleton_path) if skeleton_path is not None else SKELETON_PATH

    evidence = load_window_evidence(data_root, initial_capital=initial_capital)
    (data_root / "window_evidence.json").write_text(
        json.dumps(evidence, indent=2, default=str), encoding="utf-8")

    if run_tests:
        evidence["regression"] = _run_regression(ROOT)
        (data_root / "window_evidence.json").write_text(
            json.dumps(evidence, indent=2, default=str), encoding="utf-8")

    fmt = _fmt(evidence)
    skeleton = skeleton_path.read_text(encoding="utf-8")
    for marker, replacement in _replacement_map(fmt):
        # Whitespace-normalized match: a frozen skeleton that wraps a marker
        # across lines (e.g. `[FILL from\n   `risk_metrics_report(...)`]`) must
        # still be filled. `\s+` accepts any run of spaces/newlines/indent.
        pattern = re.compile(re.escape(marker).replace(r"\ ", r"\s+"))
        count = len(pattern.findall(skeleton))
        if count != 1:
            raise RuntimeError(
                f"report marker {marker!r} found {count} times (expected 1) — "
                f"the frozen skeleton changed; review before regenerating")
        skeleton = pattern.sub(replacement, skeleton, count=1)
    report_path.write_text(_GENERATED_BANNER + skeleton, encoding="utf-8")
    return {"evidence": evidence, "fill": fmt}


def main() -> int:
    parser = argparse.ArgumentParser(
        description="NiftyShield Stage-2 PAPER window report assembler (E007 Phase B)")
    parser.add_argument("--data-root", default="data/nifty_shield",
                        help="window evidence root")
    parser.add_argument("--report", default=str(REPORT_PATH),
                        help="PAPER Validation Report path (generated output)")
    parser.add_argument("--skeleton", default=str(SKELETON_PATH),
                        help="frozen marker-bearing template (default: the "
                             "committed .skeleton.md)")
    parser.add_argument("--run-tests", action="store_true",
                        help="run the full platform regression suite (slow)")
    args = parser.parse_args()

    result = assemble(data_root=Path(args.data_root).resolve(),
                      report_path=Path(args.report),
                      skeleton_path=Path(args.skeleton),
                      run_tests=args.run_tests)
    print(f"counting sessions: {result['evidence']['counting']['sessions_counting']} "
          f"(raw {result['evidence']['counting']['sessions_total']})")
    print(f"counting round-trips: {result['evidence']['counting']['round_trips_counting']} "
          f"(raw {result['evidence']['counting']['round_trips_total']})")
    print(f"filled report: {args.report}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
