"""Build the forward-volatility PublishedArtifact v2 (MSRP Phase 5A, A1 authoring).

Reads the candle store over the FROZEN development window (2023-01-02 -> 2025-12-31),
computes the dossier RV/HAR features, fits the OLS, and writes the immutable artifact
directory (metadata / evidence_rules / model / provenance / checksum).

This is an AUTHORING tool. It runs once; its output is frozen. The held-out window
(2026-01-01 -> 2026-07-03) is NEVER read here (dossier S1/S8).

Usage::

    python scripts/msrp/build_forward_vol_artifact.py
"""

import hashlib
import json
import os
import sys
from datetime import datetime
from pathlib import Path

import duckdb
import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

from core.msi.msrp.forward_vol import (  # noqa: E402
    FEATURE_NAMES,
    fit_har_rv_vix,
)

# --- Frozen, dossier-mandated windows ---------------------------------------
DEV_START = "2023-01-02"
DEV_END = "2025-12-31"
# Held-out is sealed; never read by this authoring tool.

NIFTY_50 = "NSE_INDEX|Nifty 50"
INDIA_VIX = "NSE_INDEX|India VIX"

CANDLES_1M = ROOT / "data" / "market_data" / "nse" / "candles" / "1m"
CANDLES_1D = ROOT / "data" / "market_data" / "nse" / "candles" / "1d"

ARTIFACT_DIR = ROOT / "core" / "msi" / "artifacts" / "forward_vol_v2"

DOSSIER_COMMIT = "d9233b1"
ARTIFACT_ID = "msrp-forward-vol-v2"
ARTIFACT_VERSION = "v1.0.0"
SCHEMA_VERSION = "1.0"
COMPAT_VERSION = "1.0"
RUNTIME_COMPAT = "msi-v1.0"
LATENT_VARIABLE = "expected_next_day_realized_vol"
DIMENSION = "volatility_level"
VALIDATION_ID = "val-msrp-forward-vol-v2-pending"


def _iter_duckdb_days(root: Path, start: str, end: str):
    start_d = pd.Timestamp(start).date()
    end_d = pd.Timestamp(end).date()
    for f in sorted(root.glob("*.duckdb")):
        try:
            d = pd.Timestamp(f.stem).date()
        except ValueError:
            continue
        if start_d <= d <= end_d:
            yield f


def load_nifty_1m_closes_by_day() -> dict:
    """Per-trading-day 1m close array for Nifty 50 over the dev window."""
    closes_by_day = {}
    for f in _iter_duckdb_days(CANDLES_1M, DEV_START, DEV_END):
        con = duckdb.connect(str(f), read_only=True)
        try:
            rows = con.execute(
                "SELECT timestamp, close FROM candles WHERE symbol = ? ORDER BY timestamp",
                [NIFTY_50],
            ).fetchall()
        finally:
            con.close()
        if not rows:
            continue
        day = pd.Timestamp(rows[0][0]).normalize()
        closes_by_day[day] = np.array([float(r[1]) for r in rows], dtype=float)
    return closes_by_day


def load_vix_daily_close() -> pd.Series:
    """India VIX daily close over the dev window, indexed by trading day."""
    records = []
    for f in _iter_duckdb_days(CANDLES_1D, DEV_START, DEV_END):
        con = duckdb.connect(str(f), read_only=True)
        try:
            rows = con.execute(
                "SELECT timestamp, close FROM candles WHERE symbol = ?",
                [INDIA_VIX],
            ).fetchall()
        finally:
            con.close()
        for ts, close in rows:
            records.append((pd.Timestamp(ts).normalize(), float(close)))
    idx = pd.DatetimeIndex([r[0] for r in records], name="date")
    return pd.Series([r[1] for r in records], index=idx, name="vix")


def _render_model_py(coeffs: dict) -> str:
    """Render the frozen artifact model.py with fitted coefficients as literals."""
    return f'''"""Frozen PublishedArtifact v2 for the forward-volatility hypothesis.

GENERATED by scripts/msrp/build_forward_vol_artifact.py from the frozen MSRP Phase-1
Research Dossier (commit {DOSSIER_COMMIT}). Do not edit by hand; coefficients are
frozen OLS estimates on the development window {DEV_START} -> {DEV_END}. Any change
requires a new artifact version under a new pre-registration.

Model (dossier S7, log specification)::

    log RV_{{t+1}} = b0 + b1 log RV^(d)_t + b2 log RV^(w)_t
                   + b3 log RV^(m)_t + b4 log VIX_t + e_t

Evaluates pre-built Evidence (rv_daily, rv_weekly, rv_monthly, vix_close) into a
MarketState carrying the named estimate "{LATENT_VARIABLE}" with state-dependent
uncertainty (Phase-2 finding Mo2).
"""

import math
from datetime import datetime
from typing import Dict, Tuple

from core.msi.contracts.artifact import ArtifactMetadata, PublishedArtifact
from core.msi.contracts.estimate import Estimate
from core.msi.contracts.evidence import Evidence
from core.msi.contracts.market_state import MarketState

# --- Frozen coefficients (dev window {DEV_START} -> {DEV_END}, OLS) ----------
B0 = {coeffs["b0"]!r}
B1 = {coeffs["b1"]!r}
B2 = {coeffs["b2"]!r}
B3 = {coeffs["b3"]!r}
B4 = {coeffs["b4"]!r}
SIGMA = {coeffs["sigma"]!r}
N_OBS = {coeffs["n_obs"]!r}

_LATENT_VARIABLE = "{LATENT_VARIABLE}"
_DIMENSION = "{DIMENSION}"
_FEATURE_TYPES = {FEATURE_NAMES!r}

_METADATA = ArtifactMetadata(
    artifact_id="{ARTIFACT_ID}",
    artifact_version="{ARTIFACT_VERSION}",
    schema_version="{SCHEMA_VERSION}",
    validation_id="{VALIDATION_ID}",
    publication_timestamp=datetime(2026, 7, 6, 0, 0, 0),
    compatibility_version="{COMPAT_VERSION}",
    runtime_compatibility="{RUNTIME_COMPAT}",
    provenance_reference="prov-msrp-forward-vol-v2",
)

_EVIDENCE_RULES: Dict[str, object] = {{
    "features": [
        {{
            "name": "rv_daily",
            "source": "{NIFTY_50}",
            "field": "close",
            "transform": "rv_intraday",
            "description": "1-day realized vol: sqrt(sum of squared intraday 1m log-returns)",
        }},
        {{
            "name": "rv_weekly",
            "source": "{NIFTY_50}",
            "field": "close",
            "transform": "har_weekly_5d",
            "description": "mean of RV over the last 5 trading days (HAR weekly aggregate)",
        }},
        {{
            "name": "rv_monthly",
            "source": "{NIFTY_50}",
            "field": "close",
            "transform": "har_monthly_22d",
            "description": "mean of RV over the last 22 trading days (HAR monthly aggregate)",
        }},
        {{
            "name": "vix_close",
            "source": "{INDIA_VIX}",
            "field": "close",
            "transform": "identity",
            "description": "India VIX closing level (option-implied forward vol)",
        }},
    ],
    "lookback_days": 22,
    "required_symbols": ["{NIFTY_50}", "{INDIA_VIX}"],
    "rule_format_version": "1.0",
}}


class ForwardVolatilityArtifact(PublishedArtifact):
    """Frozen HAR-RV+VIX PublishedArtifact v2 (MSI-007).

    Deterministic: identical Evidence -> identical MarketState. Applies the frozen
    log-linear predictor and emits the named estimate with a state-dependent
    (level-scaled) predictive uncertainty.
    """

    metadata = _METADATA

    def get_evidence_rules(self) -> Dict[str, object]:
        return _EVIDENCE_RULES

    def evaluate(self, evidence: Tuple[Evidence, ...]) -> MarketState:
        values: Dict[str, float] = {{}}
        for e in evidence:
            values[e.evidence_type] = e.evidence_value

        rv_daily = values.get("rv_daily")
        rv_weekly = values.get("rv_weekly")
        rv_monthly = values.get("rv_monthly")
        vix = values.get("vix_close")
        if not all(v is not None and v > 0.0 for v in (rv_daily, rv_weekly, rv_monthly, vix)):
            raise ValueError(
                "ForwardVolatilityArtifact requires positive rv_daily, rv_weekly, "
                "rv_monthly, vix_close evidence"
            )

        mu = (
            B0
            + B1 * math.log(rv_daily)
            + B2 * math.log(rv_weekly)
            + B3 * math.log(rv_monthly)
            + B4 * math.log(vix)
        )
        value = math.exp(mu + (SIGMA ** 2) / 2.0)
        uncertainty = value * math.sqrt(math.exp(SIGMA ** 2) - 1.0)

        estimate = Estimate(
            latent_variable=_LATENT_VARIABLE,
            value=value,
            uncertainty=uncertainty,
            dimension=_DIMENSION,
        )
        # evaluation_timestamp = the evidence's own as-of date (point-in-time provenance).
        # All four features are required (validated above), so evidence is non-empty here;
        # there is no sentinel floor — a historical evaluation is stamped with its actual
        # evidence date, not a future constant.
        latest_ts = max(e.construction_timestamp for e in evidence)
        return MarketState(evaluation_timestamp=latest_ts, estimates=(estimate,))
'''


def _write_json(path: Path, obj: dict) -> None:
    path.write_text(json.dumps(obj, indent=2, sort_keys=False) + "\n", encoding="utf-8")


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def main() -> None:
    print(f"[1/5] Loading Nifty 50 1m closes for dev window {DEV_START} -> {DEV_END} ...")
    closes_by_day = load_nifty_1m_closes_by_day()
    print(f"      {len(closes_by_day)} trading days of 1m data")

    print(f"[2/5] Loading India VIX daily close ...")
    vix = load_vix_daily_close()
    print(f"      {len(vix)} VIX observations")

    print(f"[3/5] Computing RV + HAR features + OLS fit ...")
    from core.msi.msrp.forward_vol import compute_daily_rv

    rv = compute_daily_rv(closes_by_day)
    coeffs = fit_har_rv_vix(rv, vix, DEV_START, DEV_END)
    print(f"      n_obs={coeffs['n_obs']}  sigma={coeffs['sigma']:.6f}")
    print(f"      b0={coeffs['b0']:.6f} b1={coeffs['b1']:.6f} b2={coeffs['b2']:.6f} "
          f"b3={coeffs['b3']:.6f} b4={coeffs['b4']:.6f}")

    print(f"[4/5] Writing artifact to {ARTIFACT_DIR} ...")
    ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

    metadata = {
        "artifact_id": ARTIFACT_ID,
        "artifact_version": ARTIFACT_VERSION,
        "schema_version": SCHEMA_VERSION,
        "validation_id": VALIDATION_ID,
        "publication_timestamp": "2026-07-06T00:00:00",
        "compatibility_version": COMPAT_VERSION,
        "runtime_compatibility": RUNTIME_COMPAT,
        "provenance_reference": "prov-msrp-forward-vol-v2",
        "supported_runtime_versions": [RUNTIME_COMPAT],
        "supported_ontology_versions": [SCHEMA_VERSION],
        "supported_contract_versions": [COMPAT_VERSION],
        "description": (
            "Frozen HAR-RV+VIX forward-volatility artifact (MSRP Phase 5A). "
            "Predicts next-day Nifty 50 realized volatility regime; emits the named "
            f"estimate '{LATENT_VARIABLE}' with state-dependent uncertainty."
        ),
        "created_by": "MSRP Phase 5A Implementation Engineer",
        "engine": "python",
    }
    _write_json(ARTIFACT_DIR / "metadata.json", metadata)

    evidence_rules = {
        "features": [
            {"name": "rv_daily", "source": NIFTY_50, "field": "close",
             "transform": "rv_intraday",
             "description": "1-day realized vol: sqrt(sum of squared intraday 1m log-returns)"},
            {"name": "rv_weekly", "source": NIFTY_50, "field": "close",
             "transform": "har_weekly_5d",
             "description": "mean of RV over the last 5 trading days (HAR weekly aggregate)"},
            {"name": "rv_monthly", "source": NIFTY_50, "field": "close",
             "transform": "har_monthly_22d",
             "description": "mean of RV over the last 22 trading days (HAR monthly aggregate)"},
            {"name": "vix_close", "source": INDIA_VIX, "field": "close",
             "transform": "identity",
             "description": "India VIX closing level (option-implied forward vol)"},
        ],
        "lookback_days": 22,
        "required_symbols": [NIFTY_50, INDIA_VIX],
        "rule_format_version": "1.0",
    }
    _write_json(ARTIFACT_DIR / "evidence_rules.json", evidence_rules)

    model_py = _render_model_py(coeffs)
    (ARTIFACT_DIR / "model.py").write_text(model_py, encoding="utf-8")

    provenance = {
        "originating_research": f"MSRP Phase 1 Research Dossier (commit {DOSSIER_COMMIT})",
        "validation_id": VALIDATION_ID,
        "inference_contract_version": COMPAT_VERSION,
        "ontology_version": SCHEMA_VERSION,
        "publication_event": {
            "event_id": "pub-msrp-forward-vol-v2-001",
            "timestamp": "2026-07-06T00:00:00",
            "publisher": "MSRP Phase 5A Implementation Engineer",
            "artifact_id": ARTIFACT_ID,
            "artifact_version": ARTIFACT_VERSION,
        },
        "research_provenance": {
            "methodology": (
                "HAR-RV with exogenous VIX regressor, log specification; OLS on dev window "
                f"{DEV_START} -> {DEV_END}; coefficients frozen into the artifact."
            ),
            "model_form": (
                "log RV_{t+1} = b0 + b1 log RV^(d) + b2 log RV^(w) + b3 log RV^(m) + b4 log VIX"
            ),
            "training_period": f"{DEV_START} -> {DEV_END}",
            "validation_period": None,
            "features_used": list(FEATURE_NAMES),
            "latent_variable": LATENT_VARIABLE,
            "dossier_commit": DOSSIER_COMMIT,
            "fit_n_obs": coeffs["n_obs"],
            "residual_sigma": coeffs["sigma"],
            "notes": (
                "Coefficients frozen. Held-out window sealed until Phase 6. "
                "Uncertainty is the log-normal predictive SD (Phase-2 finding Mo2, "
                "state-dependent). Parameter-estimation uncertainty not modelled (Mo3)."
            ),
        },
    }
    _write_json(ARTIFACT_DIR / "provenance.json", provenance)

    print(f"[5/5] Computing checksums ...")
    content_files = ["metadata.json", "evidence_rules.json", "model.py", "provenance.json"]
    file_hashes = {
        fname: _sha256_bytes((ARTIFACT_DIR / fname).read_bytes()) for fname in content_files
    }
    combined = _sha256_bytes("".join(file_hashes[f] for f in content_files).encode())
    _write_json(
        ARTIFACT_DIR / "checksum.sha256",
        {
            "algorithm": "sha256",
            "files": file_hashes,
            "combined_hash": combined,
        },
    )
    print(f"\nDONE. Artifact written to {ARTIFACT_DIR}")
    print(f"  files: {sorted(p.name for p in ARTIFACT_DIR.iterdir() if p.is_file())}")


if __name__ == "__main__":
    main()
